# Generated by Django 3.2.4 on 2021-07-09 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ExtensionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_fonc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_serie', models.TextField(blank=True, null=True)),
                ('quantite', models.IntegerField()),
                ('type', models.CharField(max_length=180)),
                ('marque', models.CharField(max_length=180)),
                ('accessoires', models.TextField(blank=True, null=True)),
                ('descriptif', models.TextField(blank=True, null=True)),
                ('debut', models.DateField()),
                ('fin', models.DateField(blank=True, null=True)),
                ('reprise', models.DateField(blank=True, null=True)),
                ('duree', models.DecimalField(decimal_places=1, max_digits=2)),
                ('unite_duree', models.CharField(choices=[('J', 'jour'), ('S', 'semaine'), ('M', 'mois')], max_length=180)),
                ('nom_emprunteur', models.CharField(max_length=180)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geprete.fournisseur')),
                (
                    'ingenieur_responsable',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geprete.extensionuser'),
                ),
                ('unite_fonctionnelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geprete.service')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentPret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=180)),
                (
                    'fichier',
                    models.FileField(
                        blank=True,
                        help_text='Sélectionnez dans vos dossiers le fichier à ajouter',
                        max_length=255,
                        upload_to='',
                        verbose_name='Fichier',
                    ),
                ),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('num_pret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geprete.pret')),
            ],
        ),
    ]
