# Generated by Django 3.2.4 on 2021-08-02 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geprete', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pret',
            name='debut',
            field=models.DateField(default=None),
        ),
        migrations.CreateModel(
            name='Gprete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inventaire', models.CharField(max_length=2, null=True)),
                ('debutp', models.DateField(default=None)),
                ('finp', models.DateField(blank=True, null=True)),
                ('dureep', models.DecimalField(decimal_places=1, max_digits=2)),
                ('nom_p', models.CharField(max_length=180)),
                ('num_tel_p', models.CharField(max_length=180)),
                ('nom_r', models.CharField(max_length=180)),
                ('num_tel_r', models.CharField(max_length=180)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('unite_fonctionnelle_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geprete.service')),
            ],
        ),
    ]
