# Generated by Django 3.2.4 on 2021-08-09 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geprete', '0002_auto_20210802_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentGessaye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=180)),
                (
                    'fichier',
                    models.FileField(
                        blank=True,
                        help_text='Sélectionnez dans vos dossiers le fichier à ajouter',
                        max_length=255,
                        upload_to='',
                        verbose_name='Fichier',
                    ),
                ),
                ('commentaire', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Geprete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marque', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('num_inv', models.TextField(blank=True, null=True)),
                (
                    'contact_preteur',
                    models.TextField(blank=True, help_text='nom et numéro de télépone de la personne qui fait le prêt', null=True),
                ),
                (
                    'contact_receveur',
                    models.TextField(
                        blank=True, help_text='nom et numéro de télépone de la personne qui reçoit le prêt', null=True
                    ),
                ),
                ('debut_pret', models.DateField(blank=True, null=True)),
                ('fin_pret', models.DateField(blank=True, null=True)),
                ('duree_pret', models.DecimalField(decimal_places=1, max_digits=2)),
                ('comm_pret', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gessaye',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_de_serie', models.TextField(blank=True, null=True)),
                ('quantite', models.IntegerField()),
                ('type', models.CharField(max_length=180)),
                ('marque', models.CharField(max_length=180)),
                ('accessoires', models.TextField(blank=True, null=True)),
                ('descriptif', models.TextField(blank=True, null=True)),
                ('debut', models.DateField()),
                ('fin', models.DateField(blank=True, null=True)),
                ('reprise', models.DateField(blank=True, null=True)),
                ('duree', models.DecimalField(decimal_places=1, max_digits=2)),
                ('unite_duree', models.CharField(choices=[('J', 'jour'), ('S', 'semaine'), ('M', 'mois')], max_length=180)),
                ('nom_emprunteur', models.CharField(max_length=180)),
                ('commentaire', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gprete',
            name='unite_fonctionnelle_p',
        ),
        migrations.RemoveField(
            model_name='pret',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='pret',
            name='ingenieur_responsable',
        ),
        migrations.RemoveField(
            model_name='pret',
            name='unite_fonctionnelle',
        ),
        migrations.AlterField(
            model_name='extensionuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='DocumentPret',
        ),
        migrations.DeleteModel(
            name='Gprete',
        ),
        migrations.DeleteModel(
            name='Pret',
        ),
        migrations.AddField(
            model_name='gessaye',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geprete.fournisseur'),
        ),
        migrations.AddField(
            model_name='gessaye',
            name='ingenieur_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geprete.extensionuser'),
        ),
        migrations.AddField(
            model_name='gessaye',
            name='unite_fonctionnelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geprete.service'),
        ),
        migrations.AddField(
            model_name='geprete',
            name='uf_preteur',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uf_preteur', to='geprete.service'
            ),
        ),
        migrations.AddField(
            model_name='geprete',
            name='uf_receveur',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uf_receveur', to='geprete.service'
            ),
        ),
        migrations.AddField(
            model_name='documentgessaye',
            name='num_pret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geprete.gessaye'),
        ),
    ]
