# Generated by Django 3.2.4 on 2021-08-17 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0040_alter_alert_dernier_email'),
        ('geprete', '0004_auto_20210809_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geprete',
            name='comm_pret',
        ),
        migrations.AlterField(
            model_name='geprete',
            name='contact_preteur',
            field=models.TextField(blank=True, help_text='Nom et numéro de télépone de la personne qui fait le prêt', null=True),
        ),
        migrations.AlterField(
            model_name='geprete',
            name='contact_receveur',
            field=models.TextField(blank=True, help_text='Nom et numéro de télépone de la personne qui reçoit le prêt', null=True),
        ),
        migrations.AlterField(
            model_name='geprete',
            name='uf_preteur',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uf_preteur', to='common.uf'
            ),
        ),
        migrations.AlterField(
            model_name='geprete',
            name='uf_receveur',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uf_receveur', to='common.uf'
            ),
        ),
        migrations.AlterField(
            model_name='gessaye',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geprete.fournisseur'),
        ),
        migrations.AlterField(
            model_name='gessaye',
            name='ingenieur_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.extensionuser'),
        ),
        migrations.AlterField(
            model_name='gessaye',
            name='unite_duree',
            field=models.CharField(choices=[('J', 'jours'), ('S', 'semaines'), ('M', 'mois')], max_length=180),
        ),
        migrations.AlterField(
            model_name='gessaye',
            name='unite_fonctionnelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.uf'),
        ),
        migrations.DeleteModel(
            name='DocumentGessaye',
        ),
    ]
