# Generated by Django 3.2.4 on 2021-08-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geprete', '0005_auto_20210817_1010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='geprete',
            name='date_demande',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geprete',
            name='unite',
            field=models.CharField(choices=[('J', 'jours'), ('S', 'semaines'), ('M', 'mois')], default='jours', max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gessaye',
            name='contact_fournisseur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gessaye',
            name='coord_fournisseur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gessaye',
            name='num_ce',
            field=models.TextField(blank=True, null=True),
        ),
    ]
