# Generated by Django 3.2.4 on 2021-08-23 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geprete', '0006_auto_20210820_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geprete',
            name='date_demande',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='geprete',
            name='duree_pret',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='geprete',
            name='marque',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='geprete',
            name='type',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gessaye',
            name='contact_fournisseur',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gessaye',
            name='coord_fournisseur',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gessaye',
            name='duree',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='gessaye',
            name='nom_emprunteur',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
