# Generated by Django 3.2.4 on 2021-08-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geprete', '0007_auto_20210823_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gessaye',
            name='fournisseur',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='gessaye',
            name='num_ce',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='gessaye',
            name='numero_de_serie',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.DeleteModel(
            name='Fournisseur',
        ),
    ]
