# Generated by Django 3.2.4 on 2021-08-27 14:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0040_alter_alert_dernier_email'),
        ('geprete', '0008_auto_20210823_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geprete',
            name='date_demande',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geprete',
            name='debut_pret',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='geprete',
            name='marque',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geprete',
            name='num_inv',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='geprete',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geprete',
            name='uf_preteur',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uf_preteur', to='common.uf'
            ),
        ),
    ]
