# Generated by Django 4.0.4 on 2022-05-21 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geprete', '0009_auto_20210827_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gessaye',
            name='ingenieur_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
