# Generated by Django 4.2.7 on 2024-01-23 16:41

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('geprete', '0010_alter_gessaye_ingenieur_responsable'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='geprete',
            managers=[
                ('records', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='gessaye',
            managers=[
                ('records', django.db.models.manager.Manager()),
            ],
        ),
    ]
