# Generated by Django 3.2.3 on 2021-06-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('DI', 'Autre'),
                    ('DE', 'Devis'),
                    ('CO', 'Doc commerciale'),
                    ('CR', 'Email, courrier'),
                    ('IM', 'Photo'),
                    ('AS', 'Article scientifique'),
                    ('TR', 'Texte réglementaire'),
                    ('RE', 'Recommandations'),
                    ('RC', 'Compte-rendu'),
                    ('PM', 'Planning de mutualisation'),
                    ('BP', 'Business Plan'),
                    ('ME', 'Etude médico-économique'),
                    ('TE', 'Doc technique'),
                ],
                help_text='Choisissez le type du document à joindre',
                max_length=8,
                verbose_name='Type',
            ),
        ),
    ]
