# Generated by Django 3.2.3 on 2021-06-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_document_doc_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='sha1_hash',
        ),
        migrations.AddField(
            model_name='document',
            name='hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
