# Generated by Django 3.2.3 on 2021-06-15 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_alter_genericdocument_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericdocument',
            name='document',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='generic_document', to='document.document'
            ),
        ),
    ]
