# Generated by Django 3.2.6 on 2021-08-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_alter_document_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericdocument',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
