# Generated by Django 4.0.4 on 2022-05-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_alter_document_doc_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['hash'], name='document_do_hash_54191b_idx'),
        ),
    ]
