# Generated by Django 4.0.6 on 2022-07-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_document_document_do_hash_54191b_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('DE', 'Devis'), ('CO', 'Doc commerciale'), ('CR', 'Email, courrier'), ('IM', 'Photo'), ('AS', 'Article scientifique'), ('TR', 'Texte réglementaire'), ('RE', 'Recommandations'), ('RC', 'Compte-rendu'), ('PM', 'Planning de mutualisation'), ('BP', 'Business Plan'), ('ME', 'Etude médico-économique'), ('TE', 'Doc technique'), ('DRA', "Demande de Réalisation d'Achat"), ('REF', 'Bon de demande de réforme'), ('DI', 'Autre document'), ('PL', 'Plan, schéma')], help_text='Choisissez le type du document à joindre', max_length=8, verbose_name='Type'),
        ),
    ]
