# Generated by Django 4.0 on 2022-11-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_alter_document_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericdocument',
            name='object_id',
            field=models.CharField(max_length=64),
        ),
    ]
