# Generated by Django 4.2.3 on 2023-08-22 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('document', '0011_alter_genericdocument_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericdocument',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
    ]
