# Generated by Django 4.2.7 on 2024-01-23 16:41

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_alter_genericdocument_content_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='document',
            managers=[
                ('records', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='genericdocument',
            managers=[
                ('records', django.db.models.manager.Manager()),
            ],
        ),
    ]
