# Generated by Django 3.2.3 on 2021-05-24 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(blank=True, max_length=256, null=True)),
                ('comment_text', models.TextField()),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('modification_timestamp', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('desactivated_timestamp', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                (
                    'reply',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='generic_comment.genericcomment'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Rédacteur'
                    ),
                ),
            ],
        ),
    ]
