# Generated by Django 3.2.12 on 2022-03-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericcomment',
            name='object_id',
            field=models.CharField(max_length=256),
        ),
    ]
