# Generated by Django 4.2.7 on 2024-01-23 16:41

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('generic_comment', '0003_genericcomment_private_genericcomment_recipient_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='genericcomment',
            managers=[
                ('records', django.db.models.manager.Manager()),
            ],
        ),
    ]
