# Generated by Django 3.2.12 on 2022-03-30 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(blank=True, null=True, verbose_name='valeurs des paramètres utilisés pour calculer ces données')),
                ('timestamp', models.DateTimeField(verbose_name='date de référence des données (à laquelle les calculs se réfèrent)')),
                ('link', models.JSONField(blank=True, null=True, verbose_name='lien vers la page expliquant ces données analytiques')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='données analytiques')),
                ('context', models.JSONField(blank=True, null=True, verbose_name='informations sur le contextes du calcul')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, verbose_name='code de la source de données')),
                ('label', models.CharField(max_length=1024, verbose_name='nom de la source de données')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description longue de la source de données')),
                ('definition', models.JSONField(blank=True, null=True, verbose_name='définition de la source et notamment méthode de calcul')),
                ('parameters', models.JSONField(blank=True, null=True, verbose_name='paramètres possibles (avec définitions)')),
                ('dependencies', models.TextField(default='', help_text='Liste des codes des sources dont dépend celle-ci, séparés par des virgules', verbose_name='dépendances')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
        ),
        migrations.AddConstraint(
            model_name='datasource',
            constraint=models.UniqueConstraint(fields=('code',), name='data_source_code_is_unique'),
        ),
        migrations.AddField(
            model_name='data',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.datasource'),
        ),
    ]
