#  Copyright (c)

# Generated by Django 3.2.12 on 2022-04-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='storage_policy',
            field=models.JSONField(blank=True, null=True, verbose_name='politique de stockage/archivage'),
        ),
    ]
