#  Copyright (c) 2020 Brice Nord, Romuald Kliglich, Alexandre Jaborska, Philomène Mazand.
#  This file is part of the BiomAid distribution.
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, version 3.
#  This program is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#  General Public License for more details.
#  You should have received a copy of the GNU General Public License
#  along with this program. If not, see <http://www.gnu.org/licenses/>.
# Generated by Django 4.0 on 2022-08-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_datasource_storage_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='auto',
            field=models.BooleanField(default=False, help_text='Calcule la donnée dès que toutes les dépendances sont disponibles', verbose_name='Calcul automatique'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='cloture',
            field=models.DateTimeField(null=True, verbose_name='date de clôture'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='processor_name',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='nom du processeur de données'),
        ),
    ]
