# Generated by Django 4.0 on 2022-08-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_datasource_auto_datasource_cloture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='schedule',
            field=models.JSONField(blank=True, null=True, verbose_name='programmation temporelle'),
        ),
    ]
