# Generated by Django 4.0 on 2022-08-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_datasource_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='auto',
        ),
        migrations.AddField(
            model_name='datasource',
            name='auto2',
            field=models.JSONField(default=list, help_text='Calcule la donnée dès que toutes les dépendances sont disponibles. Liste des jeux de paramètres à calculer automatiquement.', verbose_name='Calcul automatique'),
        ),
    ]
