# Generated by Django 4.0 on 2022-08-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_rename_auto2_datasource_auto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='dependencies',
        ),
        migrations.AddField(
            model_name='datasource',
            name='inputs',
            field=models.JSONField(blank=True, help_text="Dictionnaire JSON qui donne les données d'entrée de la DataSource. Utilisées dans le calcul des dépendances et comme entrées du moteur.", null=True, verbose_name="Données d'entrée"),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='cloture',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de clôture'),
        ),
    ]
