# Generated by Django 4.0 on 2023-03-18 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_remove_datasource_dependencies_datasource_inputs_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataSource',
            new_name='DbDataSource',
        ),
    ]
