# Generated by Django 4.0 on 2022-11-20 16:22

from django.db import migrations
from django.utils.translation import gettext_lazy as _

from analytics.utils import set_datasource_in_migration

def add_datasources(apps, schema_editor):
    set_datasource_in_migration(
        'finance.orders-flaws',
        label=_("Problèmes liés aux commandes"),
        auto=[{}],
        parameters={},
        processor='orders_flaws_processor',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_remove_datasource_dependencies_datasource_inputs_and_more')
    ]

    operations = [
        migrations.RunPython(add_datasources),
    ]
