# Generated by Django 4.0 on 2022-11-20 20:10

from django.db import migrations
from django.utils.translation import gettext_lazy as _

from analytics.utils import set_datasource_in_migration

def add_datasources(apps, schema_editor):
    set_datasource_in_migration(
        'finance.dem_financial_assess',
        label=_("Suivi complet des demandes"),
        auto=[{}],
        parameters={},
        processor='dem_financial_assess',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_datasources),
    ]

