# Generated by Django 4.0 on 2023-04-09 07:25

from django.db import migrations
from django.utils.translation import gettext_lazy as _

from analytics.utils import set_datasource_in_migration


def add_datasources(apps, schema_editor):
    set_datasource_in_migration(
        'finance.immo_financial_assess',
        label=_("Suivi des immobilisations"),
        auto=[{}],
        parameters={},
        processor='immo_financial_assess',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20221120_2110'),
    ]

    operations = [
        migrations.RunPython(add_datasources),
    ]
