# Generated by Django 3.0.9 on 2020-08-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200820_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centreresponsabilite',
            name='code',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='prefix',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='pole',
            name='code',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='site',
            name='code',
            field=models.CharField(max_length=8),
        ),
        migrations.AddConstraint(
            model_name='etablissement',
            constraint=models.UniqueConstraint(fields=('prefix',), name='prefix_is_unique'),
        ),
    ]
