# Generated by Django 3.0.9 on 2020-08-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20200822_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uf',
            name='code',
            field=models.CharField(max_length=8, verbose_name='Code UF'),
        ),
    ]
