# Generated by Django 3.0.9 on 2020-08-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200822_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centreresponsabilite',
            name='cloture',
            field=models.DateField(null=True, verbose_name='date de cloture du centre de responsabilité'),
        ),
        migrations.AlterField(
            model_name='pole',
            name='cloture',
            field=models.DateField(null=True, verbose_name='date de clôture du pole'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cloture',
            field=models.DateField(null=True, verbose_name='date de clôture du service'),
        ),
        migrations.AlterField(
            model_name='site',
            name='cloture',
            field=models.DateField(null=True, verbose_name="date de clôture de l' établissement"),
        ),
        migrations.AlterField(
            model_name='uf',
            name='cloture',
            field=models.DateField(null=True, verbose_name="date de clôture de l'UF"),
        ),
    ]
