# Generated by Django 3.0.9 on 2020-08-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20200823_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='cloture',
            field=models.DateField(blank=True, default=None, null=True, verbose_name="date de clôture de l' établissement"),
        ),
        migrations.AlterField(
            model_name='centreresponsabilite',
            name='cloture',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='date de cloture du centre de responsabilité'),
        ),
        migrations.AlterField(
            model_name='pole',
            name='cloture',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='date de clôture du pole'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cloture',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='date de clôture du service'),
        ),
        migrations.AlterField(
            model_name='site',
            name='cloture',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='date de clôture du site'),
        ),
        migrations.AlterField(
            model_name='uf',
            name='cloture',
            field=models.DateField(blank=True, default=None, null=True, verbose_name="date de clôture de l'UF"),
        ),
    ]
