# Generated by Django 3.0.9 on 2020-08-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20200823_0912'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='uf',
            index=models.Index(fields=['code'], name='common_uf_code_1bff99_idx'),
        ),
        migrations.AddIndex(
            model_name='uf',
            index=models.Index(fields=['etablissement'], name='common_uf_etablis_4db5e4_idx'),
        ),
        migrations.AddIndex(
            model_name='uf',
            index=models.Index(fields=['site'], name='common_uf_site_id_5e140d_idx'),
        ),
        migrations.AddIndex(
            model_name='uf',
            index=models.Index(fields=['pole'], name='common_uf_pole_id_89c296_idx'),
        ),
        migrations.AddIndex(
            model_name='uf',
            index=models.Index(fields=['centre_responsabilite'], name='common_uf_centre__096c17_idx'),
        ),
        migrations.AddIndex(
            model_name='uf',
            index=models.Index(fields=['service'], name='common_uf_service_2b1363_idx'),
        ),
        migrations.AddIndex(
            model_name='uf',
            index=models.Index(fields=['cloture'], name='common_uf_cloture_fab2af_idx'),
        ),
        migrations.AddIndex(
            model_name='userufrole',
            index=models.Index(fields=['extension_user'], name='common_user_extensi_4b2817_idx'),
        ),
        migrations.AddIndex(
            model_name='userufrole',
            index=models.Index(fields=['uf'], name='common_user_uf_id_d28027_idx'),
        ),
    ]
