# Generated by Django 3.0.7 on 2020-09-29 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0008_auto_20200824_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acheteur',
            fields=[
                ('code', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('nom', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=30)),
                ('dect', models.CharField(max_length=30)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('nom', models.CharField(max_length=30, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date de création')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('date_modification', models.DateTimeField(auto_now=True, null=True, verbose_name='date de modification')),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=30)),
                ('commentaire', models.CharField(default=None, max_length=120)),
                ('enveloppe', models.DecimalField(decimal_places=0, max_digits=10)),
                ('anteriorite', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                (
                    'discipline',
                    models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='common.Discipline'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('nom', models.CharField(max_length=30)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.Acheteur')),
                (
                    'discipline',
                    models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='common.Discipline'),
                ),
            ],
        ),
    ]
