# Generated by Django 3.0.7 on 2020-10-20 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20201006_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertmetier',
            name='user',
        ),
        migrations.RemoveField(
            model_name='domaine',
            name='expert_metier',
        ),
        migrations.AddField(
            model_name='domaine',
            name='expert',
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.ExtensionUser'
            ),
        ),
    ]
