# Generated by Django 3.0.7 on 2020-10-20 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0021_auto_20201020_0646'),
        ('common', '0011_auto_20201020_0646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpertMetier',
        ),
    ]
