# Generated by Django 3.0.7 on 2020-10-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_delete_expertmetier'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaine',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='domaine',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='domaine',
            name='nom',
            field=models.CharField(max_length=64),
        ),
    ]
