# Generated by Django 3.1.4 on 2020-12-10 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0025_auto_20201027_0630'),
        ('common', '0013_auto_20201022_2136'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='etablissement',
            name='prefix_is_unique',
        ),
        migrations.AddField(
            model_name='domaine',
            name='parent',
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.domaine'
            ),
        ),
        migrations.AddField(
            model_name='programme',
            name='arbitre',
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.extensionuser'
            ),
        ),
        migrations.AddField(
            model_name='programme',
            name='calendrier',
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='dem.calendrier'
            ),
        ),
        migrations.AlterField(
            model_name='domaine',
            name='expert',
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.extensionuser'
            ),
        ),
        migrations.AlterField(
            model_name='programme',
            name='code',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='programme',
            name='commentaire',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='nom',
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name='domaine',
            constraint=models.UniqueConstraint(fields=('code',), name='domaine_code_is_unique'),
        ),
        migrations.AddConstraint(
            model_name='etablissement',
            constraint=models.UniqueConstraint(fields=('prefix',), name='etablissement_prefix_is_unique'),
        ),
        migrations.AddConstraint(
            model_name='programme',
            constraint=models.UniqueConstraint(fields=('code',), name='programme_code_is_unique'),
        ),
    ]
