# Generated by Django 3.1.4 on 2020-12-10 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_auto_20201210_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programme',
            old_name='commentaire',
            new_name='description',
        ),
    ]
