# Generated by Django 3.1.4 on 2021-01-08 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20201210_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='userufrole',
            name='centre_responsabilite',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.centreresponsabilite'
            ),
        ),
        migrations.AddField(
            model_name='userufrole',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.discipline'),
        ),
        migrations.AddField(
            model_name='userufrole',
            name='domaine_prefix',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='userufrole',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.etablissement'),
        ),
        migrations.AddField(
            model_name='userufrole',
            name='pole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.pole'),
        ),
        migrations.AddField(
            model_name='userufrole',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.service'),
        ),
        migrations.AlterField(
            model_name='userufrole',
            name='role_code',
            field=models.CharField(
                choices=[
                    ('CHP', 'Chef de pôle'),
                    ('ADCP', 'Adjoint au chef de pôle'),
                    ('CHS', 'Chef de service'),
                    ('RUN', "Responsable d'unité"),
                    ('CSP', 'Cadre supérieur de pôle'),
                    ('DRP', 'Directeur référent de pôle'),
                    ('CAP', 'Cadre administratif de pôle'),
                    ('AMAR', 'Assistant médico-administratif référent'),
                    ('CADS', 'Cadre supérieur'),
                    ('CAD', 'Cadre'),
                    ('COP', 'Coordonateur de pôle'),
                    ('DIR', 'Directeur adjoint'),
                    ('RMA', 'Référent matériel'),
                    ('ACH', 'Acheteur'),
                    ('EXP', 'Expert métier'),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name='userufrole',
            name='uf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.uf'),
        ),
    ]
