# Generated by Django 3.1.4 on 2021-01-12 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_auto_20210108_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='userufrole',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.site'),
        ),
    ]
