# Generated by Django 3.1.4 on 2021-01-12 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_userufrole_site'),
    ]

    operations = []
