# Generated by Django 3.1.4 on 2021-01-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_merge_20210112_0742'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userufrole',
            index=models.Index(fields=['service'], name='common_user_service_7a25c3_idx'),
        ),
        migrations.AddIndex(
            model_name='userufrole',
            index=models.Index(fields=['centre_responsabilite'], name='common_user_centre__5e5955_idx'),
        ),
        migrations.AddIndex(
            model_name='userufrole',
            index=models.Index(fields=['pole'], name='common_user_pole_id_4fe1d8_idx'),
        ),
        migrations.AddIndex(
            model_name='userufrole',
            index=models.Index(fields=['site'], name='common_user_site_id_1d7fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='userufrole',
            index=models.Index(fields=['etablissement'], name='common_user_etablis_0c654d_idx'),
        ),
        migrations.AddIndex(
            model_name='userufrole',
            index=models.Index(fields=['discipline'], name='common_user_discipl_8e732f_idx'),
        ),
        migrations.AddIndex(
            model_name='userufrole',
            index=models.Index(fields=['domaine_prefix'], name='common_user_domaine_f2c03a_idx'),
        ),
        migrations.AddIndex(
            model_name='userufrole',
            index=models.Index(fields=['role_code'], name='common_user_role_co_55e607_idx'),
        ),
    ]
