# Generated by Django 3.1.4 on 2021-01-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_auto_20210113_2145'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='extensionuser',
            index=models.Index(fields=['user'], name='common_exte_user_id_8de125_idx'),
        ),
    ]
