# Generated by Django 3.1.4 on 2021-01-17 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_auto_20210113_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.etablissement'),
        ),
    ]
