# Generated by Django 3.1.4 on 2021-01-18 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_programme_etablissement'),
    ]

    operations = []
