# Generated by Django 3.1.4 on 2021-02-03 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_merge_20210118_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarnetFournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule_fournisseur', models.CharField(default=None, max_length=60)),
                ('raison_sociale', models.CharField(default=None, max_length=60)),
                ('adresse_1_fournisseur', models.TextField(blank=True, default=None, null=True)),
                ('cp_fournisseur', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('ville_fournisseur', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('tel_fournisseur', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('fax_fournisseur', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('telex_fournisseur', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('nu_siret', models.CharField(max_length=25)),
                ('num_tva_intracommunautaire', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
        ),
        migrations.CreateModel(
            name='Cneh',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default=None, max_length=90)),
                ('Intitule', models.CharField(default=None, max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Cnehs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default=None, max_length=90)),
                ('Intitule', models.CharField(default=None, max_length=90)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'lettre_budgetaire',
                    models.CharField(
                        choices=[
                            ('A', 'DOTATION NON AFFECTEE'),
                            ('B', 'LONG SEJOUR'),
                            ('C', 'ECOLES'),
                            ('E', 'EHPAD'),
                            ('G', 'GHT'),
                            ('H', 'BUDGET PRINCIPAL'),
                            ('P', 'CAMSP'),
                            ('R', 'CENTRE RESSOURCE AUTISME'),
                        ],
                        default='H',
                        max_length=300,
                    ),
                ),
                ('code', models.CharField(max_length=25)),
                ('nom', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
        ),
        migrations.CreateModel(
            name='ContactFournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=300, null=True, verbose_name='Prenom')),
                (
                    'division',
                    models.CharField(
                        choices=[
                            ('COM', 'Commercial'),
                            ('SPE', 'Specialiste'),
                            ('MARK', 'Marketing'),
                            ('SAV', 'Service Apres Vente'),
                        ],
                        max_length=300,
                    ),
                ),
                ('telephone1', models.CharField(blank=True, max_length=300, null=True)),
                ('telephone2', models.CharField(blank=True, max_length=300, null=True)),
                ('Fax', models.CharField(blank=True, max_length=300, null=True)),
                ('mail', models.CharField(blank=True, max_length=300, null=True)),
                ('adresse_contact', models.TextField(blank=True, default=None, null=True)),
                ('cp_contact', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('ville_contact', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('commentaire', models.TextField(blank=True, default=None, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_four', models.IntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
        ),
        migrations.RemoveIndex(
            model_name='extensionuser',
            name='common_exte_user_id_8de125_idx',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='etablissement',
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='code_recon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='common.carnetfournisseur'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.etablissement'),
        ),
        migrations.AddField(
            model_name='contactfournisseur',
            name='societe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.fournisseur'),
        ),
        migrations.AddField(
            model_name='compte',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.discipline'),
        ),
        migrations.AddField(
            model_name='compte',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.etablissement'),
        ),
        migrations.AddField(
            model_name='cnehs',
            name='code_cneh',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='common.cneh'),
        ),
    ]
