# Generated by Django 3.1.4 on 2021-02-03 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_auto_20210203_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.etablissement'),
        ),
    ]
