# Generated by Django 3.1.4 on 2021-04-04 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_auto_20210224_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('niveau', models.IntegerField()),
                (
                    'intitule',
                    models.CharField(
                        blank=True, help_text="Description de l'alerte", max_length=256, null=True, verbose_name='Intitulé'
                    ),
                ),
                (
                    'categorie',
                    models.CharField(
                        blank=True, help_text="Catégorie de l'alerte", max_length=256, null=True, verbose_name='Catégorie'
                    ),
                ),
                ('donnees', models.TextField(blank=True, default=None, null=True)),
                ('lien', models.CharField(blank=True, default=None, max_length=4096, null=True)),
                ('commentaire', models.TextField(blank=True, default=None, null=True)),
                (
                    'etat',
                    models.CharField(blank=True, help_text="Etat de l'alerte", max_length=256, null=True, verbose_name='Etat'),
                ),
                ('date_activation', models.DateTimeField(verbose_name='date de dernière activation')),
                ('date_lecture', models.DateTimeField(verbose_name='date de lecture')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                (
                    'destinataire',
                    models.ForeignKey(
                        blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.extensionuser'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Alerte',
            },
        ),
    ]
