# Generated by Django 3.1.4 on 2021-04-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_alert_historique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de fin'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='date_lecture',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de lecture'),
        ),
    ]
