# Generated by Django 3.1.4 on 2021-04-04 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_auto_20210404_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='destinataire',
            field=models.ForeignKey(default=79, on_delete=django.db.models.deletion.PROTECT, to='common.extensionuser'),
        ),
    ]
