# Generated by Django 3.1.4 on 2021-04-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0033_auto_20210404_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionuser',
            name='preferences',
            field=models.TextField(
                default='{}',
                help_text="Préférences de l'utilisateur, stockées sous forme d'une chaine JSON",
                verbose_name='Préférences',
            ),
        ),
    ]
