# Generated by Django 3.1.4 on 2021-05-08 04:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0035_alert_dernier_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default=None, max_length=90, verbose_name='nom de la marque')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
        ),
        migrations.RenameField(
            model_name='cnehs',
            old_name='Intitule',
            new_name='intitule',
        ),
        migrations.RemoveField(
            model_name='cneh',
            name='Intitule',
        ),
        migrations.AddField(
            model_name='cneh',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cneh',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='date de fin'),
        ),
        migrations.AddField(
            model_name='cneh',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='date de modification'),
        ),
        migrations.AddField(
            model_name='cneh',
            name='intitule',
            field=models.CharField(default=None, max_length=90, verbose_name='Nom du CNEH'),
        ),
        migrations.AlterField(
            model_name='cneh',
            name='code',
            field=models.CharField(default=None, max_length=90, verbose_name='Code CNEH'),
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=None, max_length=90, verbose_name="Type/Modèle d'appareil")),
                ('complement', models.CharField(default=None, max_length=90, verbose_name="Compléments d'information")),
                (
                    'classe_code',
                    models.CharField(
                        blank=True,
                        choices=[('1', 'Classe 1'), ('2a', 'Classe 2a'), ('2b', 'Classe 2b'), ('3', 'Classe 3')],
                        max_length=90,
                        null=True,
                        verbose_name='Classification du DM',
                    ),
                ),
                ('date_obsolescence', models.DateField(blank=True, null=True, verbose_name="date d'obsolescence")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                (
                    'cneh_code',
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.cnehs'),
                ),
                (
                    'discipline',
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.discipline'),
                ),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.marque')),
            ],
        ),
    ]
