# Generated by Django 3.2.3 on 2021-08-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0038_alter_userufrole_role_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionuser',
            name='last_seen',
            field=models.DateTimeField(
                blank=True, help_text='Date de la dernière visite sur le portail', null=True, verbose_name='Dernière visite'
            ),
        ),
    ]
