# Generated by Django 3.2.4 on 2021-08-05 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0038_alter_userufrole_role_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=None, max_length=90, verbose_name='Code de la classe')),
                ('nom', models.CharField(default=None, max_length=90, verbose_name='Nom de la classe')),
                ('complement', models.CharField(default=None, max_length=300, verbose_name="Compléments d'information")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id_gmao', models.CharField(blank=True, max_length=300, null=True, verbose_name='ID de la GMAO')),
            ],
        ),
        migrations.CreateModel(
            name='LastUpdate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_in', models.CharField(blank=True, help_text="Table BIOM_AID impactée par l'update", max_length=256, null=True, verbose_name='Table BIOM_AID')),
                ('date_last_update', models.DateTimeField(blank=True, help_text="date de l'update", null=True, verbose_name='date dernier update')),
            ],
        ),
        migrations.AddField(
            model_name='compte',
            name='budget_montant',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='compte',
            name='exercice',
            field=models.DateField(blank=True, default=None, help_text='Exercice Budgétaire', null=True, verbose_name='Exercice Budgétaire'),
        ),
        migrations.AddField(
            model_name='marque',
            name='id_gmao',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ID de la GMAO'),
        ),
        migrations.AddField(
            model_name='type',
            name='id_gmao',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ID de la GMAO'),
        ),
        migrations.AlterField(
            model_name='marque',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='marque',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='marque',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='marque',
            name='nom',
            field=models.CharField(default=None, max_length=90, verbose_name='Nom de la marque'),
        ),
        migrations.AlterField(
            model_name='type',
            name='complement',
            field=models.TextField(default=None, verbose_name="Compléments d'information"),
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.TextField(default=None, verbose_name="Type/Modèle d'appareil"),
        ),
        migrations.AlterField(
            model_name='type',
            name='classe_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.classecode', verbose_name='Classification du DM'),
        ),
    ]
