# Generated by Django 3.2.4 on 2021-08-05 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0039_auto_20210805_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='common.discipline'),
        ),
    ]
