# Generated by Django 3.2.6 on 2021-08-22 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0040_alter_alert_dernier_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userufrole',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userufrole',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de fin'),
        ),
        migrations.AddField(
            model_name='userufrole',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='date de modification'),
        ),
    ]
