# Generated by Django 3.2.4 on 2021-09-13 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0040_alter_compte_discipline'),
        ('common', '0042_alter_alert_intitule'),
    ]

    operations = [
    ]
