# Generated by Django 3.2.4 on 2021-09-26 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0043_merge_20210913_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='centreresponsabilite',
            name='etablissement',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.etablissement'),
        ),
        migrations.AddField(
            model_name='pole',
            name='etablissement',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.etablissement'),
        ),
        migrations.AddField(
            model_name='service',
            name='etablissement',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.etablissement'),
        ),
        migrations.AddField(
            model_name='site',
            name='etablissement',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.etablissement'),
        ),
    ]
