# Generated by Django 3.2.7 on 2021-09-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0044_auto_20210926_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='code_gmao',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='code',
            field=models.CharField(default='', max_length=5),
        ),
    ]
