# Generated by Django 3.2.8 on 2021-10-10 17:26

from django.db import migrations


def change_user_type(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ct = ContentType.objects.filter(
        app_label='auth',
        model='user'
    ).first()
    if ct:
        ct.app_label = 'common'
        ct.save()


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0045_auto_20210927_1210'),
    ]

    operations = [
        migrations.RunPython(change_user_type),
    ]
