# Generated by Django 3.2.8 on 2021-10-10 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0046_auto_20211010_1926'),
        ('drachar', '0014_alter_dra_num_bon_commande'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
