# Generated by Django 3.2.8 on 2021-10-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0047_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='from_ldap',
            field=models.BooleanField(default=False, editable=False, verbose_name='LDAP user'),
        ),
    ]
