# Generated by Django 3.2.8 on 2021-10-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0048_user_from_ldap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('label', models.CharField(blank=True, max_length=256, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
