# Generated by Django 3.2.4 on 2021-11-27 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0050_auto_20211127_1118'),
        ('common', '0050_pole_date_creation'),
    ]

    operations = [
    ]
