# Generated by Django 3.2.7 on 2021-12-28 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0052_auto_20211128_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='pole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.pole'),
        ),
        migrations.AddField(
            model_name='programme',
            name='uf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.uf'),
        ),
    ]
