# Generated by Django 3.2.4 on 2022-01-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0053_auto_20211228_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compte',
            name='date_fin',
        ),
        migrations.AddField(
            model_name='compte',
            name='cloture',
            field=models.DateField(blank=True, null=True, verbose_name='date de cloture'),
        ),
    ]
