# Generated by Django 4.0.1 on 2022-01-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0054_auto_20220107_2204'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uf',
            unique_together={('etablissement', 'code', 'cloture')},
        ),
    ]
