#  Copyright (c)
#  Copyright (c)
#  Copyright (c)
# Generated by Django 3.2.11 on 2022-01-29 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0055_alter_uf_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programme',
            old_name='date_fin',
            new_name='cloture',
        ),
    ]
