# Generated by Django 3.2.12 on 2022-03-06 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('common', '0057_alter_userufrole_role_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='alert',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
