# Generated by Django 3.2.11 on 2022-05-13 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0059_alter_userufrole_role_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='date_fin',
            new_name='cloture',
        ),
        migrations.RenameField(
            model_name='classecode',
            old_name='date_fin',
            new_name='cloture',
        ),
        migrations.RenameField(
            model_name='cneh',
            old_name='date_fin',
            new_name='cloture',
        ),
        migrations.RenameField(
            model_name='cnehs',
            old_name='date_fin',
            new_name='cloture',
        ),
        migrations.RenameField(
            model_name='contactfournisseur',
            old_name='date_fin',
            new_name='cloture',
        ),
        migrations.RenameField(
            model_name='datafournisseurgef',
            old_name='date_fin',
            new_name='cloture',
        ),
        migrations.RenameField(
            model_name='discipline',
            old_name='date_fin',
            new_name='cloture',
        ),
        migrations.RenameField(
            model_name='fournisseur',
            old_name='date_fin',
            new_name='cloture',
        ),
        migrations.RenameField(
            model_name='marque',
            old_name='date_fin',
            new_name='cloture',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='date_fin',
            new_name='cloture',
        ),
        migrations.RenameField(
            model_name='userufrole',
            old_name='date_fin',
            new_name='cloture',
        ),
    ]
