#  Copyright (c)

# Generated by Django 4.0.4 on 2022-05-15 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0060_auto_20220513_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='userufrole',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
