#  Copyright (c)

# Generated by Django 4.0.4 on 2022-05-15 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def extension_user_2_user(apps, schema_editor):
    ExtModel = apps.get_model('common', 'ExtensionUser')
    UserModel = apps.get_model('common', 'User')
    records = ExtModel.objects.all()
    for record in records:
        user = UserModel.objects.get(pk=record.user.pk)

        user.titre = record.titre
        user.intitule_fonction = record.intitule_fonction
        # user.vocation_fonctionnelle = record.vocation_fonctionnelle
        user.etablissement = record.etablissement
        user.initiales = record.initiales
        user.tel_fixe = record.tel_fixe
        user.tel_dect = record.tel_dect
        user.tel_mobile = record.tel_mobile
        user.preferences = record.preferences
        user.last_seen = record.last_seen
        user.save(update_fields = ['titre', 'intitule_fonction', 'etablissement', 'initiales',
                                   'tel_fixe', 'tel_dect', 'tel_mobile', 'preferences', 'last_seen'])


    model = apps.get_model('common', 'UserUfRole')
    records = model.objects.all()
    for record in records:
        record.user = record.extension_user.user
        record.save(update_fields = ['user'])


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0061_userufrole_user'),
    ]

    operations = [
        migrations.RunPython(extension_user_2_user),
    ]
