#  Copyright (c)

# Generated by Django 4.0.4 on 2022-05-15 16:55
import django
from django.db import migrations, models

import settings


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0062_alter_userufrole_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userufrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveIndex(
            model_name='userufrole',
            name='common_user_extensi_4b2817_idx',
        ),
        migrations.RemoveField(
            model_name='extensionuser',
            name='role',
        ),
        migrations.AlterUniqueTogether(
            name='userufrole',
            unique_together={('user', 'uf', 'role_code')},
        ),
        migrations.AddIndex(
            model_name='userufrole',
            index=models.Index(fields=['user'], name='common_user_user_id_4ad5ef_idx'),
        ),
        migrations.RemoveField(
            model_name='userufrole',
            name='extension_user',
        ),
    ]
