#  Copyright (c)

# Generated by Django 4.0.4 on 2022-05-16 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0063_remove_userufrole_common_user_extensi_4b2817_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programme',
            old_name='arbitre',
            new_name='arbitre_ext',
        ),
        migrations.RemoveField(
            model_name='domaine',
            name='expert',
        ),
    ]
