#  Copyright (c)

# Generated by Django 4.0.4 on 2022-05-18 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def arbitre_ext_2_arbitre(apps, schema_editor):
    model = apps.get_model('common', 'Programme')
    records = model.objects.all()
    for record in records:
        if record.arbitre_ext:
            record.arbitre = record.arbitre_ext.user
            record.save(update_fields = ['arbitre'])

class Migration(migrations.Migration):

    dependencies = [
        ('common', '0064_rename_arbitre_programme_arbitre_ext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='arbitre',
            field=models.ForeignKey(blank=True, db_column='arbitre_new', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(arbitre_ext_2_arbitre),
    ]
