# Generated by Django 4.0.4 on 2022-05-18 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0065_programme_arbitre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='arbitre_ext',
        ),
    ]
