# Generated by Django 4.0.4 on 2022-05-21 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0066_remove_programme_arbitre_ext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='destinataire',
            new_name='destinataire_ext',
        ),
    ]
