# Generated by Django 4.0.4 on 2022-05-21 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0067_rename_destinataire_alert_destinataire_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='destinataire',
            field=models.ForeignKey(db_column='destinataire_new', default=79, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
