# Generated by Django 4.0.4 on 2022-05-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0069_remove_alert_destinataire_ext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='destinataire_ext',
        ),
    ]
