# Generated by Django 4.0.4 on 2022-05-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0070_remove_alert_destinataire_ext'),
        ('dem', '0066_remove_demande_expert_metier_ext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extensionuser',
            name='etablissement',
        ),
        migrations.RemoveField(
            model_name='extensionuser',
            name='user',
        ),
    ]
