# Generated by Django 4.0.4 on 2022-05-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geprete', '0010_alter_gessaye_ingenieur_responsable'),
        ('marche', '0010_alter_marche_acheteur'),
        ('common', '0071_remove_extensionuser_etablissement_and_more'),
        ('drachar', '0025_alter_affiliationdossierparticipants_participant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtensionUser',
        ),
    ]
