# Generated by Django 4.0 on 2022-08-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0072_delete_extensionuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='debut_arbitrage',
            field=models.DateField(blank=True, null=True, verbose_name="date de début d'arbitrage"),
        ),
    ]
