# Generated by Django 4.0 on 2022-11-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0073_programme_debut_arbitrage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='object_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
