# Generated by Django 4.0 on 2022-11-05 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('common', '0074_alter_alert_object_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('modification_datetime', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('desactivation_datetime', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.CharField(max_length=64)),
                ('role_code', models.CharField(choices=[('CHP', 'Chef de pôle'), ('ADCP', 'Adjoint au chef de pôle'), ('CHS', 'Chef de service'), ('RUN', "Responsable d'unité"), ('CSP', 'Cadre supérieur de pôle'), ('DRP', 'Directeur référent de pôle'), ('CAP', 'Cadre administratif de pôle'), ('AMAR', 'Assistant médico-administratif référent'), ('CADS', 'Cadre supérieur'), ('CAD', 'Cadre'), ('COP', 'Coordonateur de pôle'), ('DIR', 'Directeur adjoint'), ('RMA', 'Référent matériel'), ('ACH', 'Acheteur'), ('EXP', 'Expert métier'), ('RESPD', 'Responsable de domaine technique'), ('INGTX', 'Ingénieur travaux'), ('GES', 'Gestionnaire'), ('TECH', 'Technicien')], max_length=8)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.user', verbose_name='User that benefit to this role')),
            ],
        ),
    ]
