# Generated by Django 4.0 on 2022-11-05 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0075_genericrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericrole',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_role', to='common.user', verbose_name='User that created this link'),
        ),
        migrations.AlterField(
            model_name='genericrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.user', verbose_name='User that benefit this specific role on linked object'),
        ),
    ]
