# Generated by Django 4.0 on 2022-11-05 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0076_genericrole_creator_alter_genericrole_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericrole',
            old_name='desactivation_datetime',
            new_name='cloture',
        ),
    ]
