# Generated by Django 4.0 on 2022-12-24 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0078_alter_genericrole_role_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fournisseur',
            old_name='code_four',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='contactfournisseur',
            name='cloture',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de fin'),
        ),
        migrations.AlterField(
            model_name='contactfournisseur',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.etablissement'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='cloture',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de fin'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='nom',
            field=models.CharField(max_length=256),
        ),
    ]
