# Generated by Django 4.0 on 2023-02-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0079_rename_code_four_fournisseur_code_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='genericrole',
            index=models.Index(fields=['cloture'], name='gen_role_end_idx'),
        ),
        migrations.AddIndex(
            model_name='genericrole',
            index=models.Index(fields=['role_code'], name='gen_role_code_idx'),
        ),
        migrations.AddIndex(
            model_name='genericrole',
            index=models.Index(fields=['content_type', 'object_id'], name='gen_role_ref_idx'),
        ),
    ]
