# Generated by Django 4.0 on 2023-02-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0080_genericrole_gen_role_end_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_email',
            field=models.DateTimeField(blank=True, help_text='Date du dernier mail envoyé', null=True, verbose_name='Dernier message'),
        ),
    ]
