# Generated by Django 4.0 on 2023-02-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0081_user_last_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='limit',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
