# Generated by Django 4.2.1 on 2023-05-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0082_programme_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='consumed',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
