# Generated by Django 4.2.3 on 2023-07-12 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0083_programme_consumed'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.site'),
        ),
    ]
