# Generated by Django 4.2.3 on 2023-07-31 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0084_programme_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='FournisseurEtablissement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('cloture', models.DateTimeField(blank=True, null=True, verbose_name='date de fin')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.etablissement')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.fournisseur')),
            ],
        ),
    ]
