# Generated by Django 4.2.7 on 2023-12-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0085_alter_alert_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centreresponsabilite',
            name='nom',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='code',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='nom',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='domaine',
            name='nom',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='code',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='nom',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='prefix',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='pole',
            name='nom',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='programme',
            name='anteriorite',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='nom',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='service',
            name='nom',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='site',
            name='nom',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='uf',
            name='nom',
            field=models.CharField(max_length=256, verbose_name='Nom UF'),
        ),
    ]
