# Generated by Django 4.2.9 on 2024-04-07 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0085_fournisseuretablissement'),
        ('common', '0086_alter_centreresponsabilite_nom_alter_discipline_code_and_more'),
    ]

    operations = []
