# Generated by Django 4.2.7 on 2024-01-23 16:41

import django.contrib.auth.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0086_alter_centreresponsabilite_nom_alter_discipline_code_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cneh',
            managers=[
                ('records', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='compte',
            managers=[
                ('records', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='discipline',
            managers=[
                ('records', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='domaine',
            managers=[
                ('records', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='lastupdate',
            managers=[
                ('records', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='programme',
            managers=[
                ('records', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='role',
            managers=[
                ('records', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('all_records', django.contrib.auth.models.UserManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
