# Generated by Django 4.2.11 on 2024-06-17 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0087_merge_20240407_0832'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FournisseurEtablissement',
        ),
    ]
