# Generated by Django 4.2.9 on 2024-04-14 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0087_alter_cneh_managers_alter_compte_managers_and_more'),
        ('common', '0087_merge_20240407_0832'),
    ]

    operations = []
