# Generated by Django 3.1.4 on 2021-02-03 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0026_auto_20210203_2152'),
        ('marche', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'code',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('DEVIS', 'Devis'),
                            ('DC1', 'DC1'),
                            ('DC2', 'DC2'),
                            ('CCTP', 'cahier des charges'),
                            ('CCAP', 'Cahier des Clauses Administratives particulière'),
                            ('AVENANT', 'Avenant'),
                            ('COURRIER', 'Courrier'),
                            ('RC', 'Réglement de Consultation'),
                            ('PLAN', 'Planning'),
                            ('BP', 'Business Plan'),
                            ('DI', 'Autre'),
                        ],
                        help_text='Choisissez le type du document à joindre',
                        max_length=10,
                        verbose_name='Type',
                    ),
                ),
                (
                    'UNCpath',
                    models.FileField(
                        blank=True,
                        help_text='Sélectionnez dans vos dossiers le fichier à ajouter',
                        max_length=255,
                        upload_to='',
                        verbose_name='Fichier',
                    ),
                ),
                (
                    'commentaire',
                    models.CharField(
                        blank=True,
                        help_text='Vous pouvez y intégrer un commentaire pour décrire le document',
                        max_length=120,
                        verbose_name='Note',
                    ),
                ),
                ('status', models.BooleanField(default=False)),
                ('createur', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'verbose_name': 'document joint',
                'verbose_name_plural': 'documents joints',
            },
        ),
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marche.document')),
            ],
        ),
        migrations.CreateModel(
            name='FamilleAchat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('intitule', models.TextField()),
                ('commentaire', models.TextField()),
                ('montant_mini', models.DecimalField(decimal_places=0, default=None, max_digits=20)),
                ('sans_mini', models.BooleanField()),
                ('montant_maxi', models.DecimalField(decimal_places=0, default=None, max_digits=20)),
                ('sans_maxi', models.BooleanField()),
                ('quantite_mini', models.DecimalField(decimal_places=0, default=None, max_digits=20)),
                ('quantite_maxi', models.DecimalField(decimal_places=0, default=None, max_digits=20)),
                ('acquisition', models.BooleanField()),
                ('maintenance', models.BooleanField()),
                ('accessoires', models.BooleanField()),
                ('consommables', models.BooleanField()),
                ('date_notif', models.DateField()),
                ('date_debut', models.DateField()),
                ('duree', models.IntegerField()),
                ('type_reconduction', models.CharField(choices=[('Tacite', 'TACITE'), ('Expresse', 'EXPRESSE')], max_length=200)),
                (
                    'type_facturation',
                    models.CharField(choices=[('Forfaitaire', 'FORFAITAIRE'), ('Unitaire', 'UNITAIRE')], max_length=200),
                ),
                ('date_fin', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('code_four', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.fournisseur')),
                ('documents', models.ManyToManyField(blank=True, through='marche.DocumentLink', to='marche.Document')),
                ('etablissements', models.ManyToManyField(to='common.Etablissement')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=200)),
                ('intitule', models.TextField(default=None)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('date_suppression', models.DateTimeField(auto_now=True, verbose_name='date de suppression')),
            ],
        ),
        migrations.CreateModel(
            name='Suivi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeProcedure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=200)),
                ('intitule', models.TextField(default=None)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('date_suppression', models.DateTimeField(auto_now=True, verbose_name='date de suppression')),
            ],
        ),
        migrations.CreateModel(
            name='Marche',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_marche', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('intitule', models.TextField()),
                ('date_notif', models.DateField(blank=True, default=None, null=True)),
                ('date_debut', models.DateField(blank=True, default=None, null=True)),
                ('duree', models.IntegerField(blank=True, default=None, null=True, verbose_name='Durée en mois')),
                ('commentaire', models.TextField(blank=True, default=None, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                (
                    'acheteur',
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='acheteur',
                        to='common.extensionuser',
                    ),
                ),
                (
                    'expert_metier',
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='expert_metier',
                        to='common.extensionuser',
                    ),
                ),
                ('lots', models.ManyToManyField(blank=True, default=None, to='marche.Lot')),
                (
                    'procedure',
                    models.ForeignKey(
                        blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='marche.procedure'
                    ),
                ),
                ('type_procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marche.typeprocedure')),
            ],
        ),
        migrations.AddField(
            model_name='documentlink',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marche.lot'),
        ),
        migrations.AddIndex(
            model_name='documentlink',
            index=models.Index(fields=['document'], name='marche_docu_documen_75f252_idx'),
        ),
        migrations.AddIndex(
            model_name='documentlink',
            index=models.Index(fields=['lot'], name='marche_docu_lot_id_ee3336_idx'),
        ),
    ]
