# Generated by Django 3.2.3 on 2021-06-06 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0037_alter_userufrole_role_code'),
        ('marche', '0002_auto_20210203_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marche',
            name='date_debut',
            field=models.DateField(
                blank=True, default=None, help_text="Date de début d'exécution du marché", null=True, verbose_name='Début'
            ),
        ),
        migrations.AlterField(
            model_name='marche',
            name='date_notif',
            field=models.DateField(
                blank=True, default=None, help_text='Date de notification du marché', null=True, verbose_name='Notification'
            ),
        ),
        migrations.AlterField(
            model_name='marche',
            name='expert_metier',
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Expert métier référent de l'exécution de ce marché",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='expert_metier',
                to='common.extensionuser',
                verbose_name='Expert métier',
            ),
        ),
        migrations.AlterField(
            model_name='marche',
            name='intitule',
            field=models.TextField(
                help_text='Intitulé du marché (généralement le titre de la procédure qui a conduit à ce marché)',
                verbose_name='Intitulé',
            ),
        ),
        migrations.AlterField(
            model_name='marche',
            name='num_marche',
            field=models.CharField(
                blank=True,
                help_text='Numéro du marché tel que défini par le pouvoir adjudicateur',
                max_length=200,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name='marche',
            name='procedure',
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text='Procédure ayant conduit à ce marché',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='marche.procedure',
                verbose_name='Procédure',
            ),
        ),
        migrations.AlterField(
            model_name='marche',
            name='type_procedure',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='marche.typeprocedure', verbose_name='Type de procédure/marché'
            ),
        ),
    ]
