#  Copyright (c)
# Generated by Django 4.0.4 on 2022-05-20 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0066_remove_programme_arbitre_ext'),
        ('marche', '0005_auto_20220513_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marche',
            name='expert_metier',
        ),
        migrations.AddField(
            model_name='marche',
            name='expert_metier_ext',
            field=models.ForeignKey(blank=True, default=None, help_text="Expert métier référent de l'exécution de ce marché", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expert_metier_ext', to='common.extensionuser', verbose_name='Expert métier'),
        ),
    ]
