#  Copyright (c)

# Generated by Django 4.0.4 on 2022-05-20 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0066_remove_programme_arbitre_ext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marche', '0006_remove_marche_expert_metier_marche_expert_metier_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='marche',
            name='expert_metier',
            field=models.ForeignKey(blank=True, default=None, help_text="Expert métier référent de l'exécution de ce marché", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marche_comme_expert_metier', to=settings.AUTH_USER_MODEL, verbose_name='Expert métier'),
        ),
        migrations.AlterField(
            model_name='marche',
            name='expert_metier_ext',
            field=models.ForeignKey(blank=True, default=None, help_text="Expert métier référent de l'exécution de ce marché", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marche_comme_expert_metier_ext', to='common.extensionuser', verbose_name='Expert métier'),
        ),
    ]
