# Generated by Django 4.0.4 on 2022-05-20 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marche', '0008_remove_marche_expert_metier_ext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marche',
            name='expert_metier_ext',
        ),
    ]
