# Generated by Django 4.0.4 on 2022-05-21 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marche', '0009_remove_marche_expert_metier_ext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marche',
            name='acheteur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acheteur', to=settings.AUTH_USER_MODEL),
        ),
    ]
