# Generated by Django 4.0 on 2022-09-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marche', '0010_alter_marche_acheteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionMarche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hm', models.CharField(choices=[('HM1', 'Procédure en cours'), ('HM2', 'Procédure à prévoir'), ('HM3', 'HM résiduel'), ('HM4', 'HM ponctuel'), ('HM5', 'Avenant en cours'), ('HM6', 'Avenant à prévoir')], help_text="Code à saisir dans le champ 'objet de la dépense' de la commande", max_length=8, verbose_name='Code HM')),
                ('prefixe_compte', models.CharField(help_text="Préfixe (sans la lettre) des comptes pour lesquels l'exception est valide", max_length=12, verbose_name='Préfixe compte')),
                ('description', models.CharField(blank=True, help_text="Description (facultative) de l'exception", max_length=1024, null=True, verbose_name='Description')),
                ('code_fournisseur', models.IntegerField(help_text="Code (magh2) du fournisseur pour lequel l'exception est valide", verbose_name='Code fournisseur')),
                ('date_debut', models.DateField(help_text="Date de début de validité de l'exception", verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, help_text="Date de fin de validité de l'exception (facultatif)", null=True, verbose_name='Date de fin')),
                ('no_marche', models.CharField(blank=True, help_text="Numéro de marché à utiliser après la fin de la validité de l'exception", max_length=12, null=True, verbose_name='N° de marché à utiliser')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
        ),
    ]
