# Generated by Django 4.0 on 2022-11-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marche', '0011_exceptionmarche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptionmarche',
            name='code_hm',
            field=models.CharField(choices=[('HM1', 'HM1 - Procédure en cours'), ('HM2', 'HM2 - Procédure à prévoir'), ('HM3', 'HM3 - HM résiduel'), ('HM4', 'HM4 - HM ponctuel'), ('HM5', 'HM5 - Avenant en cours'), ('HM6', 'HM6 - Avenant à prévoir')], help_text="Code à saisir dans le champ 'objet de la dépense' de la commande", max_length=8, verbose_name='Code HM'),
        ),
    ]
