# Generated by Django 4.2.3 on 2023-08-22 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0085_alter_alert_content_type_and_more'),
        ('marche', '0012_alter_exceptionmarche_code_hm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='code_four',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.fournisseur'),
        ),
    ]
