# Generated by Django 3.2.10 on 2021-12-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies:list = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=256, verbose_name='External table name (SQL name, with prefix)')),
                ('definition', models.JSONField(default=dict, help_text='Full definition of external table (columns, types, etc.) to ensure each imported table is identical to created one')),
                ('update_ts', models.DateTimeField(blank=True, null=True, verbose_name='External table last update timestamp')),
            ],
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('table_name',), name='table_name_unicity'),
        ),
    ]
