# Generated by Django 3.0.5 on 2020-08-20 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('nom', models.CharField(max_length=30, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date de création')),
                ('date_fin', models.DateTimeField(null=True, verbose_name='date de fin')),
                ('date_modification', models.DateTimeField(auto_now=True, null=True, verbose_name='date de modification')),
            ],
        ),
        migrations.RemoveField(
            model_name='demande',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='domaine',
            name='plan',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.AddField(
            model_name='demande',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dem.Discipline'),
        ),
        migrations.AddField(
            model_name='domaine',
            name='discipline',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='dem.Discipline'),
        ),
    ]
