# Generated by Django 3.0.5 on 2020-08-20 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0004_programme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='discipline',
        ),
        migrations.AddField(
            model_name='demande',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dem.Programme'),
        ),
    ]
