# Generated by Django 3.0.5 on 2020-08-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0005_auto_20200820_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='date de fin'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='date de fin'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='date de fin'),
        ),
    ]
