# Generated by Django 3.0.5 on 2020-08-20 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0006_auto_20200820_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avis',
            options={'verbose_name': 'Arbitrage', 'verbose_name_plural': 'Arbitrages'},
        ),
    ]
