# Generated by Django 3.0.5 on 2020-08-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0007_auto_20200820_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='anteriorite',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
