# Generated by Django 3.0.5 on 2020-08-21 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0008_auto_20200821_1145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avis',
            new_name='Arbitrage',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='avis_commission',
        ),
        migrations.AddField(
            model_name='demande',
            name='arbitrage_commission',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='dem.Arbitrage',
                verbose_name='Arbitrage de la commission',
            ),
        ),
    ]
