# Generated by Django 3.0.9 on 2020-08-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0010_arbitrage_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='code_pole',
            field=models.CharField(default='0000', max_length=8, verbose_name='Code pôle'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='code_uf',
            field=models.CharField(
                default='0000', help_text="Code de l'UF qui va bénéficier de ce matériel", max_length=8, verbose_name='Code UF'
            ),
        ),
    ]
