# Generated by Django 3.0.9 on 2020-08-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0011_auto_20200822_1553'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='argumentairedetaille',
            index=models.Index(fields=['demande'], name='dem_argumen_demande_b17520_idx'),
        ),
        migrations.AddIndex(
            model_name='coutcomplementaire',
            index=models.Index(fields=['num_dmd'], name='dem_coutcom_num_dmd_f577fa_idx'),
        ),
        migrations.AddIndex(
            model_name='demande',
            index=models.Index(fields=['num_dmd'], name='dem_demande_num_dmd_0d7c4c_idx'),
        ),
        migrations.AddIndex(
            model_name='demande',
            index=models.Index(fields=['uf'], name='dem_demande_uf_id_80aa06_idx'),
        ),
        migrations.AddIndex(
            model_name='demande',
            index=models.Index(fields=['programme'], name='dem_demande_program_4aef76_idx'),
        ),
        migrations.AddIndex(
            model_name='demande',
            index=models.Index(fields=['arbitrage_commission'], name='dem_demande_arbitra_238b06_idx'),
        ),
        migrations.AddIndex(
            model_name='documentlink',
            index=models.Index(fields=['document'], name='dem_documen_documen_d05145_idx'),
        ),
        migrations.AddIndex(
            model_name='documentlink',
            index=models.Index(fields=['demande'], name='dem_documen_demande_6ead18_idx'),
        ),
    ]
