# Generated by Django 3.0.5 on 2020-08-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0013_auto_20200826_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='avis_cadre_sup',
            field=models.BooleanField(null=True, verbose_name='Avis cadre sup'),
        ),
        migrations.AddField(
            model_name='demande',
            name='commentaire_cadre_sup',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='nom_cadre_sup',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
