# Generated by Django 3.0.5 on 2020-08-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0014_auto_20200826_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='avis_biomed',
            field=models.BooleanField(null=True, verbose_name="Avis de l'acheteur"),
        ),
    ]
