# Generated by Django 3.0.5 on 2020-09-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0015_auto_20200827_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argumentairedetaille',
            name='commentaire_gf',
            field=models.TextField(
                blank=True,
                help_text="Précisez ici comment la demande pourrait entrainer une économie ou une recette pour l'établissement.\n            \n\nN'hésitez pas à joindre des documents (étude médico-économique, business plan...)\n            à la demande pour appuyer votre argumentation.",
                verbose_name='Précisions gains économiques',
            ),
        ),
        migrations.AlterField(
            model_name='argumentairedetaille',
            name='commentaire_im',
            field=models.TextField(
                blank=True,
                help_text="Indiquez ici quel bénéfice ce matériel pourrait apporter à la prise en charge.\n\n\n            N'hésitez pas à joindre des documents (publications, références, expériences, ...)\n            à la demande pour appuyer votre argumentation.",
                verbose_name="Précisions sur l'intérêt médical",
            ),
        ),
        migrations.AlterField(
            model_name='argumentairedetaille',
            name='commentaire_ir',
            field=models.TextField(
                blank=True,
                help_text="Indiquez ici en quoi cette demande participerait à l'innovation,            les éventuels liens avec la commission innovation pour le financement du fonctionnement.            Vous pouvez aussi préciser le nom du projet du reherche associé.            \n\nN'hésitez pas à joindre des documents (article scientifique, projet de recherche, etc.)            à la demande pour appuyer votre argumentation.",
                verbose_name='Précisions innovation/recherche',
            ),
        ),
        migrations.AlterField(
            model_name='argumentairedetaille',
            name='commentaire_m',
            field=models.TextField(
                blank=True,
                help_text="Préciser avec quel(s) autre(s) service(s) la mutualisation est envisagée,\n            selon quelles modalités (répartition des plages horaires, vacations, etc.)            \n\nN'hésitez pas à joindre des documents (planning de partage, accord autre service, CR de réunion...)\n            à la demande pour appuyer votre argumentation.",
                verbose_name='Précisions sur la mutualisation',
            ),
        ),
        migrations.AlterField(
            model_name='argumentairedetaille',
            name='commentaire_n',
            field=models.TextField(
                blank=True,
                help_text="Indiquez ici comment l'accord de la demande participerait à la notoriété de l'établissement\n            au sein du territoire et avec quelle ampleur\n\nN'hésitez pas à joindre des documents\n            (rapport de consultant, etc.) à la demande pour appuyer votre argumentation.",
                verbose_name='Précisions sur la notoriété',
            ),
        ),
        migrations.AlterField(
            model_name='argumentairedetaille',
            name='commentaire_pcp',
            field=models.TextField(
                blank=True,
                help_text="Préciser si la demande est liée à un projet du pôle ou de l'établissement\n            et le niveau de validation du projet en question.\n\n\n            N'hésitez pas à joindre des documents (descriptif du projet, validation...)\n            à la demande pour appuyer votre argumentation.",
                verbose_name='Précisions projet institutionnel',
            ),
        ),
        migrations.AlterField(
            model_name='demande',
            name='consommables_eventuels',
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Consommables éventuels (stériles ou non) associé à l'équipement demandé :\n        Types, description, quantités annuelles...",
                max_length=3000,
                null=True,
                verbose_name='Consommables',
            ),
        ),
        migrations.AlterField(
            model_name='demande',
            name='contact',
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Nom de la personne qui sera contactée pour gérer l'acquisition et/ou représenter les utilisateurs\n        lors de l'opération d'acquisition.\n        Le référent est utilisé par défaut.",
                max_length=30,
                null=True,
                verbose_name='Contact',
            ),
        ),
        migrations.AlterField(
            model_name='demande',
            name='nom_projet',
            field=models.CharField(
                default=None,
                help_text="Si plusieurs demandes concernent un même projet,             donner le même nom de projet. Sinon, le projet est la demande en elle-même (rempli automatiquement).            Sauf exception, toutes les demandes d'un même projet seront validées (ou pas) simultanément.",
                max_length=120,
                verbose_name='Nom du Projet',
            ),
        ),
        migrations.AlterField(
            model_name='demande',
            name='referent',
            field=models.CharField(
                default=None,
                help_text="Personne du service à l'origine  de la demande,             qui peut être contactée pendant l'instruction pour avoir des précisions.",
                max_length=30,
                null=True,
                verbose_name='Référent',
            ),
        ),
    ]
