# Generated by Django 3.0.7 on 2020-09-29 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_acheteur_discipline_domaine_programme'),
        ('dem', '0016_auto_20200921_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domaine',
            name='acheteur',
        ),
        migrations.RemoveField(
            model_name='domaine',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='discipline',
        ),
        migrations.AlterField(
            model_name='demande',
            name='code_acheteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.Acheteur'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='domaine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.Domaine'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.Programme'),
        ),
        migrations.DeleteModel(
            name='Acheteur',
        ),
        migrations.DeleteModel(
            name='Discipline',
        ),
        migrations.DeleteModel(
            name='Domaine',
        ),
        migrations.DeleteModel(
            name='Programme',
        ),
    ]
