# Generated by Django 3.0.7 on 2020-10-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0018_auto_20201006_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande',
            old_name='code_acheteur',
            new_name='code_expert_metier',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='montant_acheteur_total',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='montant_unitaire_acheteur',
        ),
        migrations.AddField(
            model_name='demande',
            name='montant_expertmetier_total',
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default=None,
                help_text="Montant Total estimé par l'expert métier en fonction du projet et des quantités souhaitées",
                max_digits=9,
                null=True,
                verbose_name="Montant Total estimé par l'expert métier",
            ),
        ),
        migrations.AddField(
            model_name='demande',
            name='montant_unitaire_expert_metier',
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default=None,
                help_text="Montant unitaire estimé par l'expert métier en fonction du projet",
                max_digits=9,
                null=True,
                verbose_name="Montant unitaire estimé par l'expert métier",
            ),
        ),
        migrations.AlterField(
            model_name='demande',
            name='avis_biomed',
            field=models.BooleanField(null=True, verbose_name="Avis de l'expert métier"),
        ),
    ]
