# Generated by Django 3.0.7 on 2020-10-20 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_auto_20201020_0646'),
        ('dem', '0020_auto_20201011_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='code_expert_metier',
        ),
        migrations.AddField(
            model_name='demande',
            name='expert_metier',
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.ExtensionUser'
            ),
        ),
    ]
