# Generated by Django 3.0.7 on 2020-10-21 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_delete_expertmetier'),
        ('dem', '0021_auto_20201020_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='expert_metier',
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.ExtensionUser'
            ),
        ),
    ]
