# Generated by Django 3.0.7 on 2020-10-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0022_auto_20201021_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitrage',
            name='commentaire',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='commentaire_biomed',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='commentaire_cadre_sup',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='commentaire_definitif_commission',
            field=models.TextField(
                blank=True, default=None, help_text='Commentaires définitifs de la commission concernant la demande', null=True
            ),
        ),
        migrations.AlterField(
            model_name='demande',
            name='commentaire_provisoire_commission',
            field=models.TextField(
                blank=True, default=None, help_text='Commentaires de la commission lors des auditions', null=True
            ),
        ),
        migrations.AlterField(
            model_name='demande',
            name='decision_soumission',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='commentaire',
            field=models.CharField(
                blank=True,
                help_text='Vous pouvez y intégrer un commentaire pour décrire le document',
                max_length=120,
                verbose_name='Note',
            ),
        ),
    ]
