# Generated by Django 3.1.4 on 2020-12-10 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0025_auto_20201027_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendrier',
            name='code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='calendrier',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='calendrier',
            name='nom',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='calendrier',
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='dem.calendrier'
            ),
        ),
        migrations.AddField(
            model_name='demande',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='localisation',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
