# Generated by Django 3.1.4 on 2020-12-15 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0026_auto_20201210_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendrier',
            options={'verbose_name': 'campagne recensement demandes', 'verbose_name_plural': 'campagne recensement demandes'},
        ),
    ]
