# Generated by Django 3.1.4 on 2021-01-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0027_auto_20210106_1717'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='demande',
            index=models.Index(fields=['redacteur'], name='dem_demande_redacte_88c498_idx'),
        ),
        migrations.AddIndex(
            model_name='demande',
            index=models.Index(fields=['expert_metier'], name='dem_demande_expert__b4b0bb_idx'),
        ),
        migrations.AddIndex(
            model_name='demande',
            index=models.Index(fields=['domaine'], name='dem_demande_domaine_4e23fb_idx'),
        ),
        migrations.AddIndex(
            model_name='demande',
            index=models.Index(fields=['gel'], name='dem_demande_gel_542642_idx'),
        ),
    ]
