# Generated by Django 3.1.4 on 2021-01-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0028_auto_20210113_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendrier',
            name='message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
