# Generated by Django 3.1.4 on 2021-02-08 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0030_calendrier_dispatcher'),
        ('dem', '0027_auto_20201215_0654'),
    ]

    operations = []
