# Generated by Django 3.0.7 on 2021-02-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0030_calendrier_dispatcher'),
    ]
