# Generated by Django 3.1.4 on 2021-02-23 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0031_merge_20210208_1014'),
        ('dem', '0031_auto_20210223_1447'),
    ]

    operations = []
