# Generated by Django 3.0.7 on 2021-02-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0032_merge_20210223_1941'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='calendrier',
            constraint=models.UniqueConstraint(fields=('code',), name='calendrier_code_is_unique'),
        ),
    ]
