# Generated by Django 3.0.7 on 2021-04-23 15:57

import dem.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0033_auto_20210224_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='code',
            field=models.CharField(default=0, editable=False, max_length=400),
        ),
        migrations.AlterField(
            model_name='demande',
            name='code',
            field=models.CharField(default=dem.models.increment_code_number, editable=False, max_length=400),
        ),
    ]
