# Generated by Django 3.1.4 on 2021-05-04 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0035_alert_dernier_email'),
        ('dem', '0035_auto_20210501_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitrage',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='common.discipline'),
        ),
        migrations.AddField(
            model_name='arbitrage',
            name='valeur',
            field=models.BooleanField(
                default=False,
                help_text="Si 'Vrai', cela signifie que la demande avec cet arbitrage est acceptée.",
                verbose_name="Valeur de l'arbitrage",
            ),
        ),
        migrations.AlterField(
            model_name='arbitrage',
            name='code',
            field=models.CharField(default='', max_length=8),
        ),
    ]
