# Generated by Django 3.1.4 on 2021-05-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0036_auto_20210504_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='tvx_arg_devact',
            field=models.BooleanField(default=False, help_text='TODO...', verbose_name='Augmentation des effectifs'),
        ),
        migrations.AddField(
            model_name='demande',
            name='tvx_arg_devact_comment',
            field=models.TextField(blank=True, help_text='TODO...', null=True, verbose_name='Augmentation des effectifs'),
        ),
        migrations.AddField(
            model_name='demande',
            name='tvx_arg_normes',
            field=models.BooleanField(default=False, help_text='TODO...', verbose_name="Développement d'activité"),
        ),
        migrations.AddField(
            model_name='demande',
            name='tvx_arg_normes_comment',
            field=models.TextField(blank=True, help_text='TODO...', null=True, verbose_name="Développement d'activité"),
        ),
        migrations.AddField(
            model_name='demande',
            name='tvx_arg_eqpt',
            field=models.BooleanField(default=False, help_text='TODO...', verbose_name="Arrivée d'un équipement"),
        ),
        migrations.AddField(
            model_name='demande',
            name='tvx_arg_eqpt_comment',
            field=models.TextField(blank=True, help_text='TODO...', null=True, verbose_name="Arrivée d'un équipement"),
        ),
        migrations.AddField(
            model_name='demande',
            name='tvx_arg_qvt',
            field=models.BooleanField(default=False, help_text='TODO...', verbose_name='Qualité de Vie au Travail'),
        ),
        migrations.AddField(
            model_name='demande',
            name='tvx_arg_qvt_comment',
            field=models.TextField(blank=True, help_text='TODO...', null=True, verbose_name='Qualité de Vie au Travail'),
        ),
        migrations.AddField(
            model_name='demande',
            name='tvx_arg_reorg',
            field=models.BooleanField(default=False, help_text='TODO...', verbose_name='Réorganisation des activités'),
        ),
        migrations.AddField(
            model_name='demande',
            name='tvx_arg_reorg_comment',
            field=models.TextField(blank=True, help_text='TODO...', null=True, verbose_name='Réorganisation des activités'),
        ),
        migrations.AddField(
            model_name='demande',
            name='tvx_arg_securite',
            field=models.BooleanField(default=False, help_text='TODO...', verbose_name='Sécurité des patients'),
        ),
        migrations.AddField(
            model_name='demande',
            name='tvx_arg_securite_comment',
            field=models.TextField(blank=True, help_text='TODO...', null=True, verbose_name='Sécurité des patients'),
        ),
        migrations.AddField(
            model_name='demande',
            name='tvx_arg_vetustes',
            field=models.BooleanField(default=False, help_text='TODO...', verbose_name='Locaux vétustes'),
        ),
        migrations.AddField(
            model_name='demande',
            name='tvx_arg_vetustes_comment',
            field=models.TextField(blank=True, help_text='TODO...', null=True, verbose_name='Locaux vétustes'),
        ),
        migrations.AddField(
            model_name='demande',
            name='tvx_batiment',
            field=models.CharField(
                blank=True,
                choices=[
                    ('NCHU', 'Nouveau CHU (Halls 1 et 2)'),
                    ('H3', 'Bâtiment Fontenoy (Halls 3)'),
                    ('SVP', 'Saint-Vincent de Paul'),
                    ('HN', 'Hôpital Nord'),
                ],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='demande',
            name='tvx_contrainte',
            field=models.CharField(
                blank=True,
                choices=[('LIB', 'Libération des locaux'), ('LAR', 'Locaux à risque')],
                help_text='TODO...',
                max_length=8,
                null=True,
                verbose_name='Contraintes travaux dans cette zone',
            ),
        ),
        migrations.AddField(
            model_name='demande',
            name='tvx_etage',
            field=models.CharField(
                blank=True,
                choices=[
                    ('SS', 'Sous-sol'),
                    ('RDJ', 'Rez-de-Jardin'),
                    ('RDC', 'Rez-de-Chaussée'),
                    ('1', '1er étage'),
                    ('2', '1ème étage'),
                    ('3', '3ème étage'),
                    ('4', '4ème étage'),
                    ('5', '5ème étage'),
                    ('6', '6ème étage'),
                ],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='demande',
            name='tvx_eval_confort',
            field=models.IntegerField(
                blank=True, help_text='TODO...', null=True, verbose_name='Evaluation confort patients/personnel'
            ),
        ),
        migrations.AddField(
            model_name='demande',
            name='tvx_eval_contin',
            field=models.IntegerField(
                blank=True, help_text='TODO...', null=True, verbose_name='Evaluation continuité exploitaation'
            ),
        ),
        migrations.AddField(
            model_name='demande',
            name='tvx_eval_devact',
            field=models.IntegerField(
                blank=True, help_text='TODO...', null=True, verbose_name="Evaluation développement d'activité"
            ),
        ),
        migrations.AddField(
            model_name='demande',
            name='tvx_eval_qvt',
            field=models.IntegerField(blank=True, help_text='TODO...', null=True, verbose_name='Evaluation QVT'),
        ),
        migrations.AddField(
            model_name='demande',
            name='tvx_eval_securite',
            field=models.IntegerField(blank=True, help_text='TODO...', null=True, verbose_name='Evaluation sécurité'),
        ),
        migrations.AddField(
            model_name='demande',
            name='tvx_priorite',
            field=models.CharField(
                blank=True,
                choices=[('1', 'Locaux particulièrement vétustes, travaux indispensables'), ('2', ''), ('3', ''), ('4', '')],
                help_text='TODO...',
                max_length=8,
                null=True,
                verbose_name='Priorité',
            ),
        ),
    ]
