# Generated by Django 3.1.4 on 2021-05-16 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0036_auto_20210508_0626'),
        ('dem', '0037_auto_20210515_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='discipline_dmd',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='common.discipline',
                verbose_name='Discipline',
            ),
        ),
    ]
