# Generated by Django 3.2.3 on 2021-06-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0039_auto_20210518_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='tvx_etage',
            field=models.CharField(
                blank=True,
                choices=[
                    ('SS', 'Sous-sol'),
                    ('RDJ', 'Rez-de-Jardin'),
                    ('RDC', 'Rez-de-Chaussée'),
                    ('1', '1er étage'),
                    ('2', '2ème étage'),
                    ('3', '3ème étage'),
                    ('4', '4ème étage'),
                    ('5', '5ème étage'),
                    ('6', '6ème étage'),
                ],
                max_length=8,
                null=True,
            ),
        ),
    ]
