# Generated by Django 3.2.3 on 2021-07-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0043_auto_20210612_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='tvx_contrainte_alib',
            field=models.BooleanField(
                default=False, verbose_name='Des locaux provisoires devront être aménagés pendant la période de travaux'
            ),
        ),
        migrations.AddField(
            model_name='demande',
            name='tvx_contrainte_autre',
            field=models.BooleanField(default=False, verbose_name='Autre contrainte (précisez ci-dessous)'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='tvx_arg_normes',
            field=models.BooleanField(default=False, verbose_name='Mise aux normes'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='tvx_arg_normes_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Mise aux normes'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='tvx_contrainte',
            field=models.TextField(blank=True, null=True, verbose_name='Précisions sur les contraintes'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='tvx_contrainte_lar',
            field=models.BooleanField(default=False, verbose_name='Les travaux sont situés dans une zone à risque particulier'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='tvx_contrainte_lib',
            field=models.BooleanField(default=False, verbose_name='Les locaux seront libérés'),
        ),
    ]
