# Generated by Django 3.2.3 on 2021-07-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0044_auto_20210701_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='tvx_arg_devact',
            field=models.BooleanField(default=False, verbose_name='Développement de l’activité'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='tvx_arg_devact_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Développement de l’activité'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='tvx_arg_qvt',
            field=models.BooleanField(default=False, verbose_name='Confort et/ou sécurité des personnels'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='tvx_arg_qvt_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Confort et/ou sécurité des personnels'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='tvx_arg_securite',
            field=models.BooleanField(default=False, verbose_name='Confort et/ou sécurité des patients'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='tvx_arg_securite_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Confort et/ou sécurité des patients'),
        ),
    ]
