# Generated by Django 3.2.3 on 2021-07-14 11:24

import dem.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0045_auto_20210706_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='code',
            field=models.CharField(default=dem.models.increment_code_number, editable=False, max_length=400),
        ),
    ]
