# Generated by Django 3.2.3 on 2021-07-27 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0046_alter_demande_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendrier',
            options={
                'ordering': ['message', 'code'],
                'verbose_name': 'campagne recensement demandes',
                'verbose_name_plural': 'campagne recensement demandes',
            },
        ),
    ]
