# Generated by Django 3.2.6 on 2021-08-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0048_auto_20210810_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argumentairedetaille',
            name='commentaire_or',
            field=models.TextField(
                blank=True,
                help_text="Indiquez ici quelle est l'obligation réglementaire (référence du texte) et en quoi cela participe à l'argumentation.            \n\nN'hésitez pas à joindre des documents (textes, analyse...) à la demande pour appuyer votre argumentation.",
                verbose_name="Précisions sur l'obligation réglementaire",
            ),
        ),
        migrations.AlterField(
            model_name='demande',
            name='couts_complementaires',
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Existe-t-il des coûts de consommables, de maintenance, de travaux             ou d'autres coûts lié à l'achat ou l'utilisation de ce matériel ?",
                verbose_name='Coûts de fonctionnement',
            ),
        ),
        migrations.AlterField(
            model_name='demande',
            name='prix_unitaire',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="Indiquer ici une estimation du prix unitaire de l'équipement,             en euros TTC, de l'équipement demandé. S'il s'agit d'une technique  nouvelle,             il est indispensable de joindre un devis à la demande.",
                max_digits=9,
                null=True,
                verbose_name='P.Unit. (TTC)',
            ),
        ),
    ]
