# Generated by Django 3.2.6 on 2021-09-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0049_auto_20210822_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='it_a_installer',
            field=models.TextField(blank=True, null=True, verbose_name='Produits/logiciels à installer'),
        ),
        migrations.AddField(
            model_name='demande',
            name='it_caracteristiques_minimales',
            field=models.TextField(blank=True, null=True, verbose_name='Caractéristiques minimales'),
        ),
        migrations.AddField(
            model_name='demande',
            name='it_cout_formation',
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default=None,
                help_text='Coût de la formation associée au logiciel (par personne ou pour un groupe)',
                max_digits=9,
                null=True,
                verbose_name='Coût de la formation associée',
            ),
        ),
        migrations.AddField(
            model_name='demande',
            name='nature',
            field=models.CharField(
                choices=[('EQ', 'Equipement'), ('HS', 'PC + Logiciel'), ('SW', 'Logiciel'), ('TX', 'Travaux'), ('MP', 'Multiple')],
                default='EQ',
                help_text='Nature de la demande : Matériel, logiciel, travaux...',
                max_length=2,
                verbose_name='Nature',
            ),
        ),
    ]
