# Generated by Django 3.2.6 on 2021-09-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0050_auto_20210915_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendrier',
            name='roles',
            field=models.TextField(
                blank=True,
                default=None,
                help_text='Liste des rôles (codes séparés par des virgules) ayant accès à cette campagne de rencensement',
                null=True,
                verbose_name='Rôles concernés',
            ),
        ),
    ]
