# Generated by Django 3.2.6 on 2021-09-25 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0043_merge_20210913_1334'),
        ('dem', '0051_calendrier_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendrier',
            name='discipline',
            field=models.ForeignKey(
                blank=True,
                help_text='Discipline ciblée par le recensement. Si différent de NULL, les demandes créées seront par défaut configurées pour cette discipline',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='common.discipline',
            ),
        ),
    ]
