# Generated by Django 3.2.8 on 2021-10-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0052_calendrier_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='nature',
            field=models.CharField(choices=[('SW', 'Logiciel')], default='EQ', help_text='Nature de la demande : Matériel, logiciel, travaux...', max_length=2, verbose_name='Nature'),
        ),
    ]
