# Generated by Django 3.2.8 on 2021-10-31 20:37

from django.db import migrations, models


def remove_useless_quantite_validee(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Demande = apps.get_model('dem', 'Demande')
    demandes = Demande.objects.filter(arbitrage_commission__isnull=True)
    for demande in demandes:
        if demande.quantite_validee and demande.quantite and (int(demande.quantite_validee) == int(demande.quantite) or int(demande.quantite_validee) == 1):
            demande.quantite_validee = None
            demande.save(update_fields=['quantite_validee',])


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0053_alter_demande_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='quantite_validee',
            field=models.DecimalField(blank=True, decimal_places=0, help_text="quantité d'équipements validée par commission", max_digits=4, null=True, verbose_name='Quantité validée'),
        ),
        migrations.RunPython(remove_useless_quantite_validee)
    ]
