# Generated by Django 3.2.10 on 2022-01-02 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0054_alter_demande_quantite_validee'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='campagne_redirect',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demande_redirect', to='dem.calendrier'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='date_premiere_demande',
            field=models.DateField(blank=True, default='2022-01-01', help_text="Année où la demande a été présentée la première fois à la Commission d'arbitrage", null=True, verbose_name='Première demande'),
        ),
    ]
