# Generated by Django 3.2.11 on 2022-02-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0055_auto_20220102_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='gel',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
