# Generated by Django 3.2.11 on 2022-02-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0056_alter_demande_gel'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='dispatcher_note',
            field=models.TextField(blank=True, help_text='Commentaire de la personne chargées de répartir la demande entre les programmes de la campagne de recensement', null=True, verbose_name='Note responsable campagne'),
        ),
    ]
