#  Copyright (c)
# Generated by Django 3.2.12 on 2022-03-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0057_demande_dispatcher_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='target',
            field=models.CharField(blank=True, default=None, help_text="'programme' ou 'année' cible de la demande. Si Null, la demande est immédiate. Si c'est une année, c'est l'année pour laquelle la demande sera pertinente. Ce champ sert à prévoir par anticipation des plans d'équipement, par exemple pour un gros projet ou pour le PPI.", max_length=256, null=True, verbose_name='Cible'),
        ),
    ]
