# Generated by Django 3.2.12 on 2022-03-26 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0059_alter_userufrole_role_code'),
        ('dem', '0058_demande_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendrier',
            name='discipline',
            field=models.ForeignKey(default=1, help_text='les demandes créées seront par défaut configurées pour cette discipline', on_delete=django.db.models.deletion.PROTECT, to='common.discipline'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demande',
            name='discipline_dmd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='common.discipline', verbose_name='Discipline'),
            preserve_default=False,
        ),
    ]
