# Generated by Django 3.2.11 on 2022-05-13 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0061_alter_document_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arbitrage',
            old_name='date_fin',
            new_name='cloture',
        ),
    ]
