#  Copyright (c)

# Generated by Django 4.0.4 on 2022-05-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0062_rename_date_fin_arbitrage_cloture'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='demande',
            name='dem_demande_expert__b4b0bb_idx',
        ),
        migrations.RenameField(
            model_name='demande',
            old_name='expert_metier',
            new_name='expert_metier_ext',
        ),
        migrations.AddIndex(
            model_name='demande',
            index=models.Index(fields=['expert_metier_ext'], name='dem_demande_expert__e165d0_idx'),
        ),
    ]
