#  Copyright (c)

# Generated by Django 4.0.4 on 2022-05-20 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dem', '0063_remove_demande_dem_demande_expert__b4b0bb_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='demande',
            name='dem_demande_expert__e165d0_idx',
        ),
        migrations.AddField(
            model_name='demande',
            name='expert_metier',
            field=models.ForeignKey(blank=True, db_column='expert_user', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demande_comme_expert', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='demande',
            index=models.Index(fields=['expert_metier'], name='dem_demande_expert__6648cb_idx'),
        ),
    ]
