# Generated by Django 4.0.4 on 2022-05-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0066_remove_demande_expert_metier_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='arg_commentaire_cp',
            field=models.TextField(blank=True, help_text="Précisez comment l'objet de la demande pourra améliorer le confort ou l'expérience des patients.            \n\nN'hésitez pas à joindre des documents (articles, essais...) à la demande pour appuyer votre argumentation.", verbose_name='Précisions confort patient'),
        ),
        migrations.AddField(
            model_name='demande',
            name='arg_commentaire_gf',
            field=models.TextField(blank=True, help_text="Précisez ici comment la demande pourrait entrainer une économie ou une recette pour l'établissement.\n            \n\nN'hésitez pas à joindre des documents (étude médico-économique, business plan...)\n            à la demande pour appuyer votre argumentation.", verbose_name='Précisions gains économiques'),
        ),
        migrations.AddField(
            model_name='demande',
            name='arg_commentaire_im',
            field=models.TextField(blank=True, help_text="Indiquez ici quel bénéfice ce matériel pourrait apporter à la prise en charge.\n\n\n            N'hésitez pas à joindre des documents (publications, références, expériences, ...)\n            à la demande pour appuyer votre argumentation.", verbose_name="Précisions sur l'intérêt médical"),
        ),
        migrations.AddField(
            model_name='demande',
            name='arg_commentaire_ir',
            field=models.TextField(blank=True, help_text="Indiquez ici en quoi cette demande participerait à l'innovation,            les éventuels liens avec la commission innovation pour le financement du fonctionnement.            Vous pouvez aussi préciser le nom du projet du reherche associé.            \n\nN'hésitez pas à joindre des documents (article scientifique, projet de recherche, etc.)            à la demande pour appuyer votre argumentation.", verbose_name='Précisions innovation/recherche'),
        ),
        migrations.AddField(
            model_name='demande',
            name='arg_commentaire_m',
            field=models.TextField(blank=True, help_text="Préciser avec quel(s) autre(s) service(s) la mutualisation est envisagée,\n            selon quelles modalités (répartition des plages horaires, vacations, etc.)            \n\nN'hésitez pas à joindre des documents (planning de partage, accord autre service, CR de réunion...)\n            à la demande pour appuyer votre argumentation.", verbose_name='Précisions sur la mutualisation'),
        ),
        migrations.AddField(
            model_name='demande',
            name='arg_commentaire_n',
            field=models.TextField(blank=True, help_text="Indiquez ici comment l'accord de la demande participerait à la notoriété de l'établissement\n            au sein du territoire et avec quelle ampleur\n\nN'hésitez pas à joindre des documents\n            (rapport de consultant, etc.) à la demande pour appuyer votre argumentation.", verbose_name='Précisions sur la notoriété'),
        ),
        migrations.AddField(
            model_name='demande',
            name='arg_commentaire_or',
            field=models.TextField(blank=True, help_text="Indiquez ici quelle est l'obligation réglementaire (référence du texte) et en quoi cela participe à l'argumentation.            \n\nN'hésitez pas à joindre des documents (textes, analyse...) à la demande pour appuyer votre argumentation.", verbose_name="Précisions sur l'obligation réglementaire"),
        ),
        migrations.AddField(
            model_name='demande',
            name='arg_commentaire_pcp',
            field=models.TextField(blank=True, help_text="Préciser si la demande est liée à un projet du pôle ou de l'établissement\n            et le niveau de validation du projet en question.\n\n\n            N'hésitez pas à joindre des documents (descriptif du projet, validation...)\n            à la demande pour appuyer votre argumentation.", verbose_name='Précisions projet institutionnel'),
        ),
        migrations.AddField(
            model_name='demande',
            name='arg_commentaire_pe',
            field=models.TextField(blank=True, help_text="Détaillez quel impact sur l'ergonomie ou le confort du personnel pourrait avoir la demande            \n\nN'hésitez pas à joindre des documents (étude de poste, etc.) à la demande pour appuyer votre argumentation.", verbose_name="Précisions sur l'ergonomie"),
        ),
        migrations.AddField(
            model_name='demande',
            name='arg_commentaire_r',
            field=models.TextField(blank=True, help_text="Indiquez quelles sont les recommandations (références, organisme) et comment elles sont en faveur de la demande.            \n\nN'hésitez pas à joindre des documents (recommandations) à la demande pour appuyer votre argumentation.", verbose_name='Précisions recommandations'),
        ),
        migrations.AddField(
            model_name='demande',
            name='arg_confort_patient',
            field=models.BooleanField(default=False, help_text="La demande a-t-elle en vue d'améliorer le confort patient ?", verbose_name='Confort patient'),
        ),
        migrations.AddField(
            model_name='demande',
            name='arg_confort_perso_ergo',
            field=models.BooleanField(default=False, help_text="La demande améliore-t-elle l'ergonomie ou le confort du personnel ?", verbose_name='Ergonomie du travail'),
        ),
        migrations.AddField(
            model_name='demande',
            name='arg_gain_financier',
            field=models.BooleanField(default=False, help_text='La demande permettrait-elle de réaliser des gains économiques ?', verbose_name='Gains économiques'),
        ),
        migrations.AddField(
            model_name='demande',
            name='arg_innovation_recherche',
            field=models.BooleanField(default=False, help_text='La demande concerne-t-elle un projet innovant ou de recherche ?', verbose_name='Innovation / Recherche'),
        ),
        migrations.AddField(
            model_name='demande',
            name='arg_interet_medical',
            field=models.BooleanField(default=False, help_text='Cette demande apporte-t-elle un intérêt médical ?', verbose_name='Intérêt médical'),
        ),
        migrations.AddField(
            model_name='demande',
            name='arg_mutualisation',
            field=models.BooleanField(default=False, help_text="L'équipement demandé sera-il mutualisé avec d'autres services ?", verbose_name='Mutualisation'),
        ),
        migrations.AddField(
            model_name='demande',
            name='arg_notoriete',
            field=models.BooleanField(default=False, help_text="La demande permettrait-elle d'améliorer la notoriété de l'établissement ?", verbose_name='Notoriété, Attractivité'),
        ),
        migrations.AddField(
            model_name='demande',
            name='arg_oblig_reglementaire',
            field=models.BooleanField(default=False, help_text='Existe-t-il une obligation réglementaire liée à cette demande ?', verbose_name='Obligation réglementaire'),
        ),
        migrations.AddField(
            model_name='demande',
            name='arg_projet_chu_pole',
            field=models.BooleanField(default=False, help_text="La demande est-elle liée à un projet de pôle ou au projet d'établissement ?", verbose_name='Projet institutionnel'),
        ),
        migrations.AddField(
            model_name='demande',
            name='arg_recommandations',
            field=models.BooleanField(default=False, help_text='Y a-t-il des recommandations liées à cette demande ?', verbose_name='Recommandations'),
        ),
    ]
