#  Copyright (c)

# Generated by Django 4.0.4 on 2022-05-26 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0068_transfert_argumentation_detaillee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArgumentaireDetaille',
        ),
    ]
