# Generated by Django 4.0.5 on 2022-06-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0069_delete_argumentairedetaille'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='avis_biomed',
            field=models.BooleanField(blank=True, null=True, verbose_name="Avis de l'expert métier"),
        ),
        migrations.AlterField(
            model_name='demande',
            name='avis_cadre_sup',
            field=models.BooleanField(blank=True, null=True, verbose_name='Avis cadre sup'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='couts_complementaires',
            field=models.BooleanField(blank=True, default=False, help_text="Existe-t-il des coûts de consommables, de maintenance, de travaux             ou d'autres coûts lié à l'achat ou l'utilisation de ce matériel ?", null=True, verbose_name='Coûts de fonctionnement'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='decision_validateur',
            field=models.BooleanField(blank=True, null=True, verbose_name='Décision'),
        ),
    ]
