# Generated by Django 4.0.5 on 2022-06-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0070_alter_demande_avis_biomed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='arg_commentaire_cp',
            field=models.TextField(blank=True, help_text="Précisez comment l'objet de la demande pourra améliorer le confort ou l'expérience des patients.\n\nN'hésitez pas à joindre des documents (articles, essais...) à la demande pour appuyer votre argumentation.", verbose_name='Précisions confort patient'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='arg_commentaire_gf',
            field=models.TextField(blank=True, help_text="Précisez ici comment la demande pourrait entrainer une économie ou une recette pour l'établissement. \n\nN'hésitez pas à joindre des documents (étude médico-économique, business plan...) à la demande pour appuyer votre argumentation.", verbose_name='Précisions gains économiques'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='arg_commentaire_im',
            field=models.TextField(blank=True, help_text="Indiquez ici quel bénéfice ce matériel pourrait apporter à la prise en charge. N'hésitez pas à joindre des documents (publications, références, expériences, ...) à la demande pour appuyer votre argumentation.", verbose_name="Précisions sur l'intérêt médical"),
        ),
        migrations.AlterField(
            model_name='demande',
            name='arg_commentaire_m',
            field=models.TextField(blank=True, help_text="Préciser avec quel(s) autre(s) service(s) la mutualisation est envisagée,selon quelles modalités (répartition des plages horaires, vacations, etc.)\n\nN'hésitez pas à joindre des documents (planning de partage, accord autre service, CR de réunion...)à la demande pour appuyer votre argumentation.", verbose_name='Précisions sur la mutualisation'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='arg_commentaire_n',
            field=models.TextField(blank=True, help_text="Indiquez ici comment l'accord de la demande participerait à la notoriété de l'établissementau sein du territoire et avec quelle ampleur\n\nN'hésitez pas à joindre des documents(rapport de consultant, etc.) à la demande pour appuyer votre argumentation.", verbose_name='Précisions sur la notoriété'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='arg_commentaire_or',
            field=models.TextField(blank=True, help_text="Indiquez ici quelle est l'obligation réglementaire (référence du texte) et en quoi cela participe à l'argumentation.\n\nN'hésitez pas à joindre des documents (textes, analyse...) à la demande pour appuyer votre argumentation.", verbose_name="Précisions sur l'obligation réglementaire"),
        ),
        migrations.AlterField(
            model_name='demande',
            name='arg_commentaire_pcp',
            field=models.TextField(blank=True, help_text="Préciser si la demande est liée à un projet du pôle ou de l'établissement et le niveau de validation du projet en question.\n\n N'hésitez pas à joindre des documents (descriptif du projet, validation...) à la demande pour appuyer votre argumentation.", verbose_name='Précisions projet institutionnel'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='arg_commentaire_pe',
            field=models.TextField(blank=True, help_text="Détaillez quel impact sur l'ergonomie ou le confort du personnel pourrait avoir la demande\n\nN'hésitez pas à joindre des documents (étude de poste, etc.) à la demande pour appuyer votre argumentation.", verbose_name="Précisions sur l'ergonomie"),
        ),
        migrations.AlterField(
            model_name='demande',
            name='consommables_eventuels',
            field=models.CharField(blank=True, default=None, help_text="Consommables éventuels (stériles ou non) associé à l'équipement demandé : Types, description, quantités annuelles...", max_length=3000, null=True, verbose_name='Consommables'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='contact',
            field=models.CharField(blank=True, default=None, help_text="Nom de la personne qui sera contactée pour gérer l'acquisition et/ou représenter les utilisateurs lors de l'opération d'acquisition. Le référent est utilisé par défaut.", max_length=30, null=True, verbose_name='Contact'),
        ),
    ]
