# Generated by Django 4.0.5 on 2022-07-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0072_alter_demande_nom_cadre_sup_alter_demande_redacteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='tmp_int_remain',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=9, null=True, verbose_name="Montant restant de l'enveloppe d'intéressement"),
        ),
        migrations.AddField(
            model_name='demande',
            name='tmp_int_year',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Année enveloppe intéressement'),
        ),
    ]
