# Generated by Django 4.0.6 on 2022-07-16 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0073_demande_tmp_int_remain_demande_tmp_int_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='calendrier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dem.calendrier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demande',
            name='nature',
            field=models.CharField(choices=[('EQ', 'Equipement'), ('SW', 'Logiciel'), ('TX', 'Travaux'), ('PS', 'Prestation'), ('CA', 'Consommable / Accessoire'), ('AU', 'Autre')], default='EQ', help_text='Nature de la demande : Matériel, logiciel, travaux...', max_length=2, verbose_name='Nature'),
        ),
    ]
