# Generated by Django 4.0.6 on 2022-07-23 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0072_delete_extensionuser'),
        ('dem', '0075_dem_docs_2_gen_docs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calendrier',
            new_name='Campagne',
        ),
        migrations.AlterField(
            model_name='demande',
            name='decision_validateur',
            field=models.BooleanField(blank=True, null=True, verbose_name='Approbation'),
        ),
    ]
