# Generated by Django 4.0.6 on 2022-07-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0076_rename_calendrier_campagne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='natures',
            field=models.JSONField(default=list, help_text='liste des natures de demande autorisées pour cette camapagne de recensement', verbose_name='Natures de demandes autorisées'),
        ),
    ]
