# Generated by Django 4.0.6 on 2022-07-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0077_campagne_natures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagne',
            name='natures',
            field=models.JSONField(blank=True, default=list, help_text='liste des natures de demande autorisées pour cette camapagne de recensement', verbose_name='Natures de demande autorisées'),
        ),
    ]
