# Generated by Django 4.0.6 on 2022-07-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drachar', '0028_remove_documentdracharlink_document_and_more'),
        ('dem', '0078_alter_campagne_natures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='documents',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocumentLink',
        ),
    ]
