# Generated by Django 4.0 on 2022-09-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0079_remove_documentlink_demande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='workflow_alert',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Alerte traitement'),
        ),
    ]
