# Generated by Django 4.0 on 2022-11-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0081_alter_demande_nom_organisation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='montant_bak',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='montant_total_expert_metier_bak',
        ),
        migrations.AddField(
            model_name='demande',
            name='analyse',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Analyse technique de la demande'),
        ),
    ]
