# Generated by Django 4.0 on 2022-11-20 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0082_remove_demande_montant_bak_and_more'),
        ('dem', '0082_remove_demande_state_code'),
    ]

    operations = [
    ]
