# Generated by Django 4.0 on 2023-02-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0082_remove_demande_montant_bak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='date_premiere_demande',
            field=models.DateField(blank=True, default='2023-01-01', help_text="Année où la demande a été présentée la première fois à la Commission d'arbitrage", null=True, verbose_name='Première demande'),
        ),
    ]
