# Generated by Django 4.2.6 on 2024-03-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0085_alter_campagne_dispatcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='date_premiere_demande',
            field=models.DateField(
                blank=True,
                default='2024-01-01',
                help_text="Année où la demande a été présentée la première fois à la Commission d'arbitrage",
                null=True,
                verbose_name='Première demande',
            ),
        ),
    ]
