# Generated by Django 4.2.7 on 2024-01-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0085_alter_campagne_dispatcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='date_premiere_demande',
            field=models.DateField(
                blank=True,
                default='2024-01-01',
                help_text="Année où la demande a été présentée la première fois à la Commission d'arbitrage",
                null=True,
                verbose_name='Première demande',
            ),
        ),
        migrations.AlterField(
            model_name='demande',
            name='materiel_existant',
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Matériel existant concerné par la demande de remplacement ou d'évolution.",
                max_length=1024,
                null=True,
                verbose_name='Matériel concerné',
            ),
        ),
    ]
