# Generated by Django 4.2.7 on 2024-01-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0086_alter_demande_date_premiere_demande_and_more'),
        ('dem', '0086_remove_demande_state_code'),
    ]

    operations = []
