# Generated by Django 4.2.7 on 2024-01-23 16:41

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('dem', '0087_merge_20240123_1740'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='arbitrage',
            managers=[
                ('records', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='campagne',
            managers=[
                ('records', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='coutcomplementaire',
            managers=[
                ('records', django.db.models.manager.Manager()),
            ],
        ),
    ]
