# Generated by Django 3.1.4 on 2021-02-03 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dem', '0030_calendrier_dispatcher'),
        ('marche', '0002_auto_20210203_2152'),
        ('common', '0026_auto_20210203_2152'),
        ('drachar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliationDossierParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ContactLivraison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Champs automatique', max_length=50, null=True)),
                (
                    'nom',
                    models.CharField(
                        default=None, help_text='Nom Contact pour la livraison', max_length=50, verbose_name='Nom contact livraison'
                    ),
                ),
                (
                    'prenom',
                    models.CharField(
                        default=None,
                        help_text='Prénom Contact pour la livraison',
                        max_length=50,
                        verbose_name='Prénom contact livraison',
                    ),
                ),
                (
                    'coordonnees',
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=None,
                        help_text='Numéro à appeler si nécessaire pour la livraison',
                        max_digits=10,
                        null=True,
                        verbose_name='Telephone du contact',
                    ),
                ),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                (
                    'etablissement',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='common.etablissement',
                        verbose_name="Etablissement d'affiliation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='DocumentDossierLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dem.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentDracharLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dem.document')),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('num_dossier', models.AutoField(primary_key=True, serialize=False)),
                ('nom_dossier', models.TextField(default=None)),
                ('proprietaire', models.CharField(blank=True, max_length=255, null=True)),
                ('date_deadline', models.DateField(blank=True, null=True, verbose_name='date butoire')),
                (
                    'priorite_status',
                    models.CharField(
                        choices=[('1', 'Haute'), ('2', 'Normale'), ('3', 'Basse')],
                        default=2,
                        max_length=3,
                        verbose_name='Status de la Priorité',
                    ),
                ),
                (
                    'priorite_classement',
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text='classement de la priorité',
                        null=True,
                        verbose_name='Classement Priorité',
                    ),
                ),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('document', models.ManyToManyField(blank=True, through='drachar.DocumentDossierLink', to='dem.Document')),
                (
                    'participants',
                    models.ManyToManyField(blank=True, through='drachar.AffiliationDossierParticipants', to='common.ExtensionUser'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Dra',
            fields=[
                ('num_dra', models.AutoField(primary_key=True, serialize=False)),
                ('intitule', models.TextField(default=None)),
                ('num_devis', models.CharField(default=None, max_length=120, verbose_name='N° devis')),
                ('date_devis', models.DateField(default=None, verbose_name='date du devis')),
                (
                    'num_bon_commande',
                    models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='N° devis'),
                ),
                ('date_commande', models.DateField(blank=True, null=True, verbose_name='date de commande')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                (
                    'contact_fournisseur',
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='common.contactfournisseur',
                    ),
                ),
                (
                    'contact_livraison',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='drachar.contactlivraison',
                        verbose_name='contact pour la livraison',
                    ),
                ),
                ('documents', models.ManyToManyField(blank=True, through='drachar.DocumentDracharLink', to='dem.Document')),
                (
                    'expert_metier',
                    models.ForeignKey(
                        blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.extensionuser'
                    ),
                ),
                (
                    'fournisseur',
                    models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='common.fournisseur'),
                ),
                (
                    'num_dossier',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='drachar.dossier',
                        verbose_name='Dossier de travail',
                    ),
                ),
                (
                    'num_marche',
                    models.ForeignKey(
                        default=0, on_delete=django.db.models.deletion.PROTECT, to='marche.marche', verbose_name='Marché utilisé'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Previsionnel',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                (
                    'solder_ligne',
                    models.BooleanField(
                        default=0,
                        help_text="cocher la case s'il n'y a pas d'autre achat sur cette ligne de demande.",
                        null=True,
                        verbose_name='Solder la ligne du prévisionnel',
                    ),
                ),
                (
                    'budget',
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=None,
                        help_text='Budget alloué à la demande par la commission.',
                        max_digits=9,
                        null=True,
                        verbose_name='Budget alloué à la demande',
                    ),
                ),
                ('commentaire', models.TextField(blank=True, null=True)),
                (
                    'date_estimative_mes',
                    models.DateTimeField(blank=True, null=True, verbose_name='date estimative de mise en service'),
                ),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                (
                    'expert',
                    models.ForeignKey(
                        blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.extensionuser'
                    ),
                ),
                (
                    'num_dmd',
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='dem.demande',
                        verbose_name='Numéro de la demande',
                    ),
                ),
                (
                    'programme',
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='common.programme',
                        verbose_name='Numéro de programme',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('num_ligne', models.AutoField(primary_key=True, serialize=False)),
                (
                    'a_inventorier',
                    models.BooleanField(
                        help_text="cocher la case s'il faut créer un inventaire pour les équipements de cette ligne.",
                        null=True,
                        verbose_name='Appareil à inventorier ?',
                    ),
                ),
                ('classe', models.CharField(choices=[('1', '1'), ('2A', '2A'), ('2B', '2B'), ('3', '3')], max_length=90)),
                (
                    'modele',
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Type/Modèle de l'appareil",
                        max_length=120,
                        null=True,
                        verbose_name='Type/Modèle',
                    ),
                ),
                (
                    'marque',
                    models.CharField(
                        blank=True, default=None, help_text="Marque de l'appareil", max_length=120, null=True, verbose_name='Marque'
                    ),
                ),
                (
                    'reference',
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text='référence fournisseur',
                        max_length=90,
                        null=True,
                        verbose_name='référence',
                    ),
                ),
                (
                    'descriptif',
                    models.TextField(
                        blank=True, default=None, help_text='Descritif du produit', null=True, verbose_name='référence'
                    ),
                ),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, default=None, max_digits=15)),
                ('tva', models.CharField(choices=[('20%', '0.2')], max_length=15)),
                (
                    'ref_mut',
                    models.CharField(choices=[('NON', 'NON'), ('REFORME', 'REFORME'), ('MUTATION', 'MUTATION')], max_length=15),
                ),
                (
                    'eqpt_recup',
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="N° inventaire de l'équipemetn récupéré",
                        max_length=90,
                        null=True,
                        verbose_name='N° inventaire',
                    ),
                ),
                (
                    'pv_reforme',
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text='N° PV de réforme',
                        max_length=90,
                        null=True,
                        verbose_name='N° PV de réforme',
                    ),
                ),
                ('garantie', models.DecimalField(decimal_places=0, max_digits=10)),
                ('date_reception', models.DateField(blank=True, null=True, verbose_name='date de livraison')),
                ('date_mes', models.DateField(blank=True, null=True, verbose_name='date de mise en service')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                (
                    'cneh',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='common.cnehs', verbose_name='code Cneh du produit commandé'
                    ),
                ),
                (
                    'famille_achat',
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='marche.familleachat'),
                ),
                (
                    'num_compte',
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='common.compte',
                        verbose_name='Numéro de compte',
                    ),
                ),
                ('num_dra', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='drachar.dra')),
                (
                    'num_previsionnel',
                    models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='drachar.previsionnel'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire_cache_acheteur', models.TextField(verbose_name="Remarque de l'acheteur")),
                ('commentaire_visible_acheteur', models.TextField(verbose_name="Commentaire de l'acheteur")),
                (
                    'etape1_code',
                    models.CharField(
                        choices=[
                            ('0', 'NA'),
                            ('1', 'OK'),
                            ('2', 'En cours'),
                            ('3', 'En attente'),
                            ('4', 'Bloqué'),
                            ('5', 'Annulé'),
                        ],
                        max_length=90,
                    ),
                ),
                ('etape1_comment', models.TextField(verbose_name='Definition du Besoin')),
                (
                    'etape2_code',
                    models.CharField(
                        choices=[
                            ('0', 'NA'),
                            ('1', 'OK'),
                            ('2', 'En cours'),
                            ('3', 'En attente'),
                            ('4', 'Bloqué'),
                            ('5', 'Annulé'),
                        ],
                        max_length=90,
                    ),
                ),
                ('etape2_comment', models.TextField(verbose_name='Essais')),
                (
                    'etape3_code',
                    models.CharField(
                        choices=[
                            ('0', 'NA'),
                            ('1', 'OK'),
                            ('2', 'En cours'),
                            ('3', 'En attente'),
                            ('4', 'Bloqué'),
                            ('5', 'Annulé'),
                        ],
                        max_length=90,
                    ),
                ),
                ('etape3_comment', models.TextField(verbose_name='Devis')),
                (
                    'etape4_code',
                    models.CharField(
                        choices=[
                            ('0', 'NA'),
                            ('1', 'OK'),
                            ('2', 'En cours'),
                            ('3', 'En attente'),
                            ('4', 'Bloqué'),
                            ('5', 'Annulé'),
                        ],
                        max_length=90,
                    ),
                ),
                ('etape4_comment', models.TextField(verbose_name='Marché')),
                (
                    'etape5_code',
                    models.CharField(
                        choices=[
                            ('0', 'NA'),
                            ('1', 'OK'),
                            ('2', 'En cours'),
                            ('3', 'En attente'),
                            ('4', 'Bloqué'),
                            ('5', 'Annulé'),
                        ],
                        max_length=90,
                    ),
                ),
                ('etape5_comment', models.TextField(verbose_name='Commande')),
                (
                    'etape6_code',
                    models.CharField(
                        choices=[
                            ('0', 'NA'),
                            ('1', 'OK'),
                            ('2', 'En cours'),
                            ('3', 'En attente'),
                            ('4', 'Bloqué'),
                            ('5', 'Annulé'),
                        ],
                        max_length=90,
                    ),
                ),
                ('etape6_comment', models.TextField(verbose_name='Livraison')),
                (
                    'etape7_code',
                    models.CharField(
                        choices=[
                            ('0', 'NA'),
                            ('1', 'OK'),
                            ('2', 'En cours'),
                            ('3', 'En attente'),
                            ('4', 'Bloqué'),
                            ('5', 'Annulé'),
                        ],
                        max_length=90,
                    ),
                ),
                ('etape7_comment', models.TextField(verbose_name='Mise en service')),
                (
                    'etape8_code',
                    models.CharField(
                        choices=[
                            ('0', 'NA'),
                            ('1', 'OK'),
                            ('2', 'En cours'),
                            ('3', 'En attente'),
                            ('4', 'Bloqué'),
                            ('5', 'Annulé'),
                        ],
                        max_length=90,
                    ),
                ),
                ('etape8_comment', models.TextField(verbose_name='Réaffectation')),
                ('num_dmd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dem.demande')),
            ],
        ),
        migrations.AddField(
            model_name='documentdracharlink',
            name='dra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drachar.dra'),
        ),
        migrations.AddField(
            model_name='documentdossierlink',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drachar.dossier'),
        ),
        migrations.AddField(
            model_name='affiliationdossierparticipants',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drachar.dossier'),
        ),
        migrations.AddField(
            model_name='affiliationdossierparticipants',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.extensionuser'),
        ),
        migrations.AddIndex(
            model_name='documentdracharlink',
            index=models.Index(fields=['document'], name='drachar_doc_documen_43fe20_idx'),
        ),
        migrations.AddIndex(
            model_name='documentdracharlink',
            index=models.Index(fields=['dra'], name='drachar_doc_dra_id_765580_idx'),
        ),
        migrations.AddIndex(
            model_name='documentdossierlink',
            index=models.Index(fields=['document'], name='drachar_doc_documen_fbb293_idx'),
        ),
        migrations.AddIndex(
            model_name='documentdossierlink',
            index=models.Index(fields=['dossier'], name='drachar_doc_dossier_ab6f29_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliationdossierparticipants',
            index=models.Index(fields=['dossier'], name='drachar_aff_dossier_0669f3_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliationdossierparticipants',
            index=models.Index(fields=['participant'], name='drachar_aff_partici_45c07d_idx'),
        ),
    ]
