# Generated by Django 3.1.4 on 2021-02-12 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drachar', '0002_auto_20210203_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='date_deadline',
        ),
        migrations.AddField(
            model_name='dossier',
            name='commentaire',
            field=models.TextField(
                blank=True, default=None, help_text="Commentaire sur l'avancement du dossier", null=True, verbose_name='Commentaire'
            ),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='date de modification'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='date butoir'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='proprietaire',
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Propriétaire'
            ),
            preserve_default=False,
        ),
    ]
