# Generated by Django 3.1.4 on 2021-02-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drachar', '0003_auto_20210212_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previsionnel',
            name='solder_ligne',
            field=models.BooleanField(
                default=False,
                help_text="cocher la case s'il n'y a pas d'autre achat sur cette ligne de demande.",
                verbose_name='Solder la ligne du prévisionnel',
            ),
        ),
    ]
