# Generated by Django 3.1.4 on 2021-02-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drachar', '0004_auto_20210214_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='previsionnel',
            name='commentaire_public',
            field=models.TextField(
                blank=True,
                help_text="Commentaire qui sera affiché aussi à l'utilisateur / le demandeur",
                null=True,
                verbose_name='Commentaire public',
            ),
        ),
        migrations.AddField(
            model_name='previsionnel',
            name='ligne_dra94',
            field=models.IntegerField(
                blank=True,
                help_text='Utilisé pour faire le lien automatique avec  DRA94 (suivi financier, notamment)',
                null=True,
                verbose_name='Numéro de ligne dans DRA94',
            ),
        ),
        migrations.AddField(
            model_name='previsionnel',
            name='suivi_achat',
            field=models.TextField(
                blank=True,
                help_text='Idem case équivalente dans le tableau de suivi (notamment pour la gestion du préfixe)',
                null=True,
                verbose_name='Suivi Achat',
            ),
        ),
        migrations.AddField(
            model_name='previsionnel',
            name='suivi_appro',
            field=models.TextField(
                blank=True,
                help_text='Idem case équivalente dans le tableau de suivi (notamment pour la gestion du préfixe)',
                null=True,
                verbose_name='Suivi Appro/Dra',
            ),
        ),
        migrations.AddField(
            model_name='previsionnel',
            name='suivi_besoin',
            field=models.TextField(
                blank=True,
                help_text='Idem case équivalente dans le tableau de suivi (notamment pour la gestion du préfixe)',
                null=True,
                verbose_name='Suivi Besoin',
            ),
        ),
        migrations.AddField(
            model_name='previsionnel',
            name='suivi_mes',
            field=models.TextField(
                blank=True,
                help_text='Idem case équivalente dans le tableau de suivi (notamment pour la gestion du préfixe)',
                null=True,
                verbose_name='Suivi MES',
            ),
        ),
        migrations.AddField(
            model_name='previsionnel',
            name='suivi_offre',
            field=models.TextField(
                blank=True,
                help_text='Idem case équivalente dans le tableau de suivi (notamment pour la gestion du préfixe)',
                null=True,
                verbose_name='Suivi Offre',
            ),
        ),
        migrations.AlterField(
            model_name='previsionnel',
            name='commentaire',
            field=models.TextField(
                blank=True,
                help_text="Commentaire qui ne sera affiché qu'aux experts/acheteurs",
                null=True,
                verbose_name='Commentaire privé',
            ),
        ),
    ]
