# Generated by Django 3.1.4 on 2021-02-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drachar', '0005_auto_20210215_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previsionnel',
            name='date_estimative_mes',
            field=models.DateTimeField(
                blank=True, help_text='date estimative de mise en service', null=True, verbose_name='Mise en service'
            ),
        ),
        migrations.AlterField(
            model_name='previsionnel',
            name='ligne_dra94',
            field=models.IntegerField(
                blank=True,
                help_text='Numéro de ligne dans DRA94 : Utilisé pour faire le lien automatique avec  DRA94 (suivi financier, notamment)',
                null=True,
                verbose_name='Ligne',
            ),
        ),
    ]
