# Generated by Django 3.1.4 on 2021-02-19 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drachar', '0006_auto_20210215_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previsionnel',
            name='ligne_dra94',
        ),
    ]
