# Generated by Django 3.1.4 on 2021-02-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drachar', '0007_remove_previsionnel_ligne_dra94'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previsionnel',
            name='date_estimative_mes',
            field=models.DateTimeField(
                blank=True, help_text='Date estimative de mise en service', null=True, verbose_name='Estimation MES'
            ),
        ),
        migrations.AlterField(
            model_name='previsionnel',
            name='suivi_achat',
            field=models.TextField(
                blank=True,
                help_text='Idem case équivalente dans le tableau de suivi (notamment pour la gestion du préfixe)',
                null=True,
                verbose_name='Marché',
            ),
        ),
        migrations.AlterField(
            model_name='previsionnel',
            name='suivi_appro',
            field=models.TextField(
                blank=True,
                help_text='Idem case équivalente dans le tableau de suivi (notamment pour la gestion du préfixe)',
                null=True,
                verbose_name='Commande',
            ),
        ),
        migrations.AlterField(
            model_name='previsionnel',
            name='suivi_besoin',
            field=models.TextField(
                blank=True,
                help_text='Idem case équivalente dans le tableau de suivi (notamment pour la gestion du préfixe)',
                null=True,
                verbose_name='Définition du Besoin',
            ),
        ),
        migrations.AlterField(
            model_name='previsionnel',
            name='suivi_mes',
            field=models.TextField(
                blank=True,
                help_text='Idem case équivalente dans le tableau de suivi (notamment pour la gestion du préfixe)',
                null=True,
                verbose_name='Mise en service',
            ),
        ),
        migrations.AlterField(
            model_name='previsionnel',
            name='suivi_offre',
            field=models.TextField(
                blank=True,
                help_text='Idem case équivalente dans le tableau de suivi (notamment pour la gestion du préfixe)',
                null=True,
                verbose_name='Devis',
            ),
        ),
    ]
