# Generated by Django 3.1.4 on 2021-03-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drachar', '0008_auto_20210219_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='previsionnel',
            name='montant_commande',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text='Montant total commandé sur cette ligne de prévisionnel',
                max_digits=11,
                null=True,
                verbose_name='Montant commandé',
            ),
        ),
        migrations.AddField(
            model_name='previsionnel',
            name='montant_estime',
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default=None,
                help_text="Meilleure estimation du montant total : Soit l'enveloppe, soit une réévaluation de l'enveloppe après précision du besoin, soit montant total commandé",
                max_digits=9,
                null=True,
                verbose_name='Montant estimé',
            ),
        ),
    ]
