# Generated by Django 3.0.7 on 2021-03-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drachar', '0008_auto_20210219_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='date de fin'),
        ),
    ]
