# Generated by Django 3.1.4 on 2021-03-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drachar', '0009_auto_20210319_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='previsionnel',
            name='date_debut',
            field=models.DateTimeField(
                blank=True, help_text='Date de début du traitement du dossier', null=True, verbose_name='Prise en charge'
            ),
        ),
    ]
