# Generated by Django 3.0.7 on 2021-03-31 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drachar', '0010_previsionnel_date_debut'),
        ('drachar', '0009_dossier_date_fin'),
    ]

    operations = []
