# Generated by Django 3.1.4 on 2021-03-31 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drachar', '0009_dossier_date_fin'),
        ('drachar', '0010_previsionnel_date_debut'),
    ]

    operations = []
