# Generated by Django 3.0.7 on 2021-04-02 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drachar', '0011_merge_20210331_0743'),
        ('drachar', '0011_merge_20210331_0748'),
    ]

    operations = []
