# Generated by Django 3.1.4 on 2021-05-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drachar', '0012_merge_20210402_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='previsionnel',
            name='interface',
            field=models.TextField(
                blank=True, null=True, verbose_name='Interface avec les autres logiciels (DRA94, magh2, Asset+, ...)'
            ),
        ),
    ]
