# Generated by Django 3.2.6 on 2021-09-21 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drachar', '0013_previsionnel_interface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dra',
            name='num_bon_commande',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='N° commande'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    verbose_name='Propriétaire'),
        ),
    ]
