# Generated by Django 3.2.11 on 2022-02-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drachar', '0014_alter_dra_num_bon_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='previsionnel',
            name='suivi_autorisation',
            field=models.TextField(blank=True, help_text='Idem case équivalente dans le tableau de suivi (notamment pour la gestion du préfixe)', null=True, verbose_name='Autorisation'),
        ),
        migrations.AddField(
            model_name='previsionnel',
            name='suivi_etude',
            field=models.TextField(blank=True, help_text='Idem case équivalente dans le tableau de suivi (notamment pour la gestion du préfixe)', null=True, verbose_name='Etude'),
        ),
        migrations.AddField(
            model_name='previsionnel',
            name='suivi_execution',
            field=models.TextField(blank=True, help_text='Idem case équivalente dans le tableau de suivi (notamment pour la gestion du préfixe)', null=True, verbose_name='Exécution'),
        ),
        migrations.AddField(
            model_name='previsionnel',
            name='suivi_preparation',
            field=models.TextField(blank=True, help_text='Idem case équivalente dans le tableau de suivi (notamment pour la gestion du préfixe)', null=True, verbose_name='Préparation'),
        ),
        migrations.AddField(
            model_name='previsionnel',
            name='suivi_reception',
            field=models.TextField(blank=True, help_text='Idem case équivalente dans le tableau de suivi (notamment pour la gestion du préfixe)', null=True, verbose_name='Réception'),
        ),
    ]
