#  Copyright (c)

# Generated by Django 4.0.4 on 2022-05-20 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drachar', '0016_auto_20220513_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dra',
            old_name='expert_metier',
            new_name='expert_metier_ext',
        ),
    ]
