#  Copyright (c)

# Generated by Django 4.0.4 on 2022-05-20 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0066_remove_programme_arbitre_ext'),
        ('drachar', '0017_rename_expert_metier_dra_expert_metier_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='dra',
            name='expert_metier',
            field=models.ForeignKey(blank=True, db_column='expert', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dra_comme_expert', to='common.extensionuser'),
        ),
        migrations.AlterField(
            model_name='dra',
            name='expert_metier_ext',
            field=models.ForeignKey(blank=True, db_column='expert_old', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dra_comme_expert_ext', to='common.extensionuser'),
        ),
    ]
