# Generated by Django 4.0.4 on 2022-05-20 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drachar', '0019_remove_dra_expert_metier_ext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dra',
            name='expert_metier_ext',
        ),
    ]
