# Generated by Django 4.0.4 on 2022-05-21 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drachar', '0020_remove_dra_expert_metier_ext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previsionnel',
            old_name='expert',
            new_name='expert_ext',
        ),
    ]
