# Generated by Django 4.0.4 on 2022-05-21 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0071_remove_extensionuser_etablissement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drachar', '0024_remove_previsionnel_expert_ext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliationdossierparticipants',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participe', through='drachar.AffiliationDossierParticipants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possede_dossier', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
        migrations.AlterField(
            model_name='dra',
            name='expert_metier',
            field=models.ForeignKey(blank=True, db_column='expert', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dra_comme_expert', to=settings.AUTH_USER_MODEL),
        ),
    ]
