# Generated by Django 4.0.5 on 2022-06-25 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0072_delete_extensionuser'),
        ('drachar', '0025_alter_affiliationdossierparticipants_participant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='previsionnel',
            name='uf',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.uf', verbose_name='UF bénéficiaire'),
        ),
    ]
