# Generated by Django 4.0.5 on 2022-06-25 04:21

from django.db import migrations, models
import django.db.models.deletion

def demande_uf_to_previsionnel(apps, schema_editor):
    model = apps.get_model('drachar', 'Previsionnel')
    records = model.objects.all()
    for record in records:
        record.uf = record.num_dmd.uf
        record.save(update_fields = ['uf'])


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0072_delete_extensionuser'),
        ('drachar', '0026_previsionnel_uf'),
    ]

    operations = [
        migrations.RunPython(demande_uf_to_previsionnel),
        migrations.AlterField(
            model_name='previsionnel',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.uf', verbose_name='UF bénéficiaire'),
        ),
    ]
