# Generated by Django 4.0.6 on 2022-07-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drachar', '0027_alter_previsionnel_uf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='document',
        ),
        migrations.RemoveField(
            model_name='dra',
            name='documents',
        ),
        migrations.DeleteModel(
            name='DocumentDossierLink',
        ),
        migrations.DeleteModel(
            name='DocumentDracharLink',
        ),
    ]
