# Generated by Django 4.0 on 2022-11-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drachar', '0029_auto_20221120_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='previsionnel',
            name='analyse',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Analyse technique du prévisionnel'),
        ),
    ]
