# Generated by Django 4.0 on 2022-12-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drachar', '0030_previsionnel_analyse'),
    ]

    operations = [
        migrations.AddField(
            model_name='previsionnel',
            name='montant_engage',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Montant total engagé sur cette ligne de prévisionnel (détecté automatiquement)', max_digits=11, null=True, verbose_name='Montant engagé'),
        ),
        migrations.AddField(
            model_name='previsionnel',
            name='montant_liquide',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Montant total des équipements inventoriés sur cette ligne de prévisionnel (détecté automatiquement)', max_digits=11, null=True, verbose_name='Montant inventaire'),
        ),
        migrations.AddField(
            model_name='previsionnel',
            name='nombre_commandes',
            field=models.IntegerField(blank=True, default=None, help_text='Nombre de commandes sur cette ligne de prévisionnel (détecté automatiquement)', null=True, verbose_name='Nombre de commandes'),
        ),
        migrations.AddField(
            model_name='previsionnel',
            name='nombre_equipements',
            field=models.IntegerField(blank=True, default=None, help_text='Montant total des équipements inventoriés sur cette ligne de prévisionnel (détecté automatiquement)', null=True, verbose_name='Montant inventaire'),
        ),
        migrations.AddField(
            model_name='previsionnel',
            name='nombre_lignes_commandes',
            field=models.IntegerField(blank=True, default=None, help_text='Nombre de lignes de commande sur cette ligne de prévisionnel (détecté automatiquement)', null=True, verbose_name='Nombre de lignes de commande'),
        ),
        migrations.AlterField(
            model_name='previsionnel',
            name='analyse',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Analyse technique du prévisionnel (détecté automatiquement)'),
        ),
    ]
