# Generated by Django 4.0 on 2022-12-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drachar', '0031_previsionnel_montant_engage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='previsionnel',
            name='valeur_inventaire',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Montant total des équipements inventoriés sur cette ligne de prévisionnel (détecté automatiquement)', max_digits=11, null=True, verbose_name='Montant inventaire'),
        ),
        migrations.AlterField(
            model_name='previsionnel',
            name='montant_liquide',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Montant total liquidé sur cette ligne de prévisionnel (détecté automatiquement)', max_digits=11, null=True, verbose_name='Montant liquidé'),
        ),
    ]
