# Generated by Django 4.0 on 2023-05-20 11:10

#
# Migration manuelle qui remplace toutes les valeurs "0.00" dans Previsionnel.montant_commande par None (NULL)
# Cette valeur 0.00 a pratiquement toujours entrée (par erreur) par dra94_update (qui est maintenant obsolète)
# lorsqu'aucune DRA n'était trouvée sur la ligne de prévisionnel
# Pour les quelques cas où cette valeur 0.00 était rentrée intentionnellement (par exemple pour un produite gratuit,
#   déjà en stock ou pour une demande annulée), cela n'aura pas d'impact car dans les calculs, 0.00 est la valeur par
#   défaut.
#

from django.db import migrations

from drachar.models import Previsionnel


def reset_previsionnel_montant_commande(apps, schema_editor):
    Previsionnel.records.filter(montant_commande=0).update(montant_commande=None)


class Migration(migrations.Migration):
    dependencies = [
        ('drachar', '0033_alter_previsionnel_nombre_equipements'),
    ]

    operations = [
        migrations.RunPython(reset_previsionnel_montant_commande),
    ]
