# Generated by Django 4.2.6 on 2024-03-07 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marche', '0013_alter_lot_code_four'),
        ('drachar', '0035_alter_dossier_proprietaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dra',
            name='programme',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.PROTECT, to='common.programme', verbose_name='Numéro de programme'
            ),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='quantite',
            field=models.PositiveIntegerField(
                blank=True, default=None, help_text='Quantité de produit souhaité', null=True, verbose_name='Quantité'
            ),
        ),
        migrations.AlterField(
            model_name='dra',
            name='num_marche',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to='marche.marche', verbose_name='Marché utilisé'
            ),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='tva',
            field=models.CharField(choices=[('20%', '0.2'), ('5,5%', '0.055')], max_length=15),
        ),
        migrations.AlterField(
            model_name='previsionnel',
            name='programme',
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='common.programme',
                verbose_name='Numéro de programme',
            ),
        ),
    ]
