# Generated by Django 4.2.11 on 2024-06-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drachar', '0035_alter_dossier_proprietaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='previsionnel',
            name='cloturer_ligne',
            field=models.BooleanField(
                default=False,
                help_text='cocher la case quand le dossier est terminé',
                verbose_name='Cloturer la ligne du prévisionnel',
            ),
        ),
    ]
