# Generated by Django 4.2.6 on 2024-03-07 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0087_fournisseuretablissement'),
        ('marche', '0013_alter_lot_code_four'),
        ('drachar', '0036_dra_programme_lignecommande_quantite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dra',
            name='num_marche',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.PROTECT, to='marche.marche', verbose_name='Marché utilisé'
            ),
        ),
        migrations.AlterField(
            model_name='previsionnel',
            name='programme',
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='common.programme',
                verbose_name='Numéro de programme',
            ),
        ),
    ]
