# Generated by Django 4.2.6 on 2024-03-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drachar', '0037_alter_dra_num_marche_alter_previsionnel_programme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignecommande',
            name='ref_mut',
            field=models.CharField(
                choices=[('NON', 'NON'), ('REFORME', 'REFORME'), ('MUTATION', 'MUTATION')], default='NON', max_length=15
            ),
        ),
    ]
